DMS Modules
opentelekomcloud/ansible-collection-cloud pull request #100
Opened 2021-03-25 08:29 UTC by SebastianGode

2021-04-22 11:17 UTC, tischrei requested changes

2021-04-22 11:17 UTC, tischrei commented on plugins/modules/dms_instance.py
> +            "location": {
leave location out.

2021-04-22 11:17 UTC, tischrei commented on plugins/modules/dms_instance.py
> +            "maintenance_end": null,
Fill most of the "null" values with corresponding values. Otherwise leave them out.

2021-04-22 11:17 UTC, tischrei commented on plugins/modules/dms_instance_topic.py
> +            "is_sync_flush": null,
chaange "null" values to corresponding vals.

2021-04-22 11:17 UTC, tischrei commented on plugins/modules/dms_message.py
> +                "error_code": null,
to many "nulls" :-D

2021-04-22 11:17 UTC, tischrei commented on tests/integration/targets/dms/tasks/main.yaml
> +    # - name: Create Kafka Instance
What's up with this quoted stuff? Leave it out if not necessary for release.

2021-06-11 08:24 UTC, SebastianGode commented on plugins/modules/dms_instance.py
> +            "location": {
Done.

2021-06-11 08:24 UTC, SebastianGode commented on plugins/modules/dms_instance_topic.py
> +            "is_sync_flush": null,
Left them out as API returns null

2021-06-11 08:24 UTC, SebastianGode commented on plugins/modules/dms_message.py
> +                "error_code": null,
Left them out as API returns null

2021-06-11 08:25 UTC, SebastianGode commented on tests/integration/targets/dms/tasks/main.yaml
> +    # - name: Create Kafka Instance
Removed

2021-06-11 10:06 UTC, tischrei approved these changes

2021-06-11 10:36 UTC, merged