VPN service module
opentelekomcloud/ansible-collection-cloud pull request #102
Opened 2021-04-23 13:34 UTC by Polina-Gubina

VPN service module

2021-04-26 11:48 UTC, anton-sidelnikov requested changes

2021-04-30 06:11 UTC, tischrei approved these changes

2021-04-30 06:24 UTC, irina-pereiaslavskaia submitted a review, later dismissed

2021-04-30 07:29 UTC, gtema requested changes
what about test that will try to simply create/delete vpn without verifying its status?

2021-04-30 07:29 UTC, gtema commented on plugins/modules/vpn_service.py
> +                if self.check_mode:
this can be actually streamlined (there's no need for existing_vpn vs updated_vpn):
```
if not self.check_mode:
    vpn = self.conn.....
self.exit(changed=True, vpn=vpn)
```

2021-04-30 07:29 UTC, gtema commented on plugins/modules/vpn_service.py
> +            else:
this can (and should) be handled through kwargs (i.e. as in https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/volume_backup.py#L116)

2021-04-30 07:29 UTC, gtema commented on plugins/modules/vpn_service.py
> +            if self.check_mode:
same as above:
```
if not self.check_mode:
    __action__
self.exit...
```

2021-04-30 07:29 UTC, gtema commented on plugins/modules/vpn_service.py
> +            if existing_vpn:
and same here:
```
if existing_vpn:
    if not self.check_mode:
      __delete
    self.exit(True)
```
but it is still fine.
The last "if" is however a bit unclear. It is more or less a default unconditional - exit(False)

2021-04-30 08:40 UTC, Polina-Gubina commented on plugins/modules/vpn_service.py
> +            else:
bur router is not required for updating

2021-04-30 08:40 UTC, Polina-Gubina commented on plugins/modules/vpn_service.py
> +                if self.check_mode:
done

2021-04-30 08:40 UTC, Polina-Gubina commented on plugins/modules/vpn_service.py
> +            if self.check_mode:
done

2021-04-30 08:40 UTC, Polina-Gubina commented on plugins/modules/vpn_service.py
> +            if existing_vpn:
done

2021-04-30 09:05 UTC, tischrei approved these changes

2021-04-30 12:32 UTC, anton-sidelnikov submitted a review, later dismissed

2021-04-30 20:16 UTC, Polina-Gubina commented
> what about test that will try to simply create/delete vpn without verifying its status?

It is impossible to delete vpn in status 'pending_create' (through openstack client it is possible, but here it raises ResourceNotFound exception),                         I can create vpn and ensure that it was successful, but then I can't delete and so I can't delete all related resources such as network and subnet

2021-06-10 07:58 UTC, gtema requested changes

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +  tenant_id:
should be project_id

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +  service_id:
This is not an info module - we have no service_id. Instead `name` should be name or id to support updating

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +        if service_id:
as above - we should have only "name" as name_or_id

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +        if tenant_id:
param must be called project_id

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +                    updated_vpn = self.conn.network.update_vpn_service(existing_vpn, **query)
and what if in update wrong router/subnet are specified? It should be placed after validating router/subnet

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +            else:
even the router/subnet is not supported for updating user might want to "recreate" VPN. To support this we compare if current router/subnet set on the VPN are matching passed args. If yes - do nothing (or update description if required), if no - drop and recreate vpn

2021-06-10 07:58 UTC, gtema commented on plugins/modules/vpn_service.py
> +            if existing_vpn:
no completely - you currently exit with changed=False even after real deletion

2021-12-23 09:54 UTC, anton-sidelnikov submitted a review, later dismissed

2022-11-29 13:42 UTC, gtema commented
please in the tests start using has_snat variable when provisioning router (like https://github.com/opentelekomcloud/ansible-collection-cloud/blob/main/tests/integration/targets/vpc_route_test/tasks/main.yaml#L45)

2023-03-02 15:50 UTC, closed without merging