first version of info module
opentelekomcloud/ansible-collection-cloud pull request #112
Opened 2021-05-21 14:27 UTC by YustinaKvr

first version of dns-recordset-info module

2021-05-26 14:45 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +
module_kwargs = dict(
        required_if=[
            ('recordset', not None,
             ['zone'])
        ]
    )

2021-05-26 14:52 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +    choices: ['ACTIVE', 'ERROR', 'DISABLE', 'FREEZE', 'PENDING_CREATE', 'PENDING_UPDATE', 'PENDING_DELETE']
please use this lower case

2021-05-26 14:52 UTC, Polina-Gubina commented on test.yml
> +      ignore_errors: yes
please add endline

2021-05-26 14:52 UTC, Polina-Gubina commented on tests/integration/targets/dns_recordset_info/tasks/main.yaml
> +      ignore_errors: yes
the same

2021-05-26 14:52 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +                    self.fail_json(msg="Zone not found")
msg="Recordset not found"

2021-06-07 07:47 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +    zone: "{{ dns_zo.zone.id }}"
zone should be example without undefined variables

2021-06-07 07:58 UTC, anton-sidelnikov requested changes

2021-06-07 07:58 UTC, anton-sidelnikov commented on tests/.gitignore
> +collections/ansible_collections/opentelekomcloud/cloud/test.yml
please remove this line

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +  soft_key:
sort_key

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +  soft_dir:
sort_dir

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +        soft_key=dict(required=False, choices=['name', 'type']),
sort_key

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +        soft_dir=dict(required=False, choices=['desc', 'asc']),
sort_dir

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +            query['soft_dir'] = self.params['soft_dir']
same mistake

2021-06-07 07:58 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +        if self.params['soft_key']:
same

2021-06-07 08:00 UTC, anton-sidelnikov requested changes

2021-06-07 08:00 UTC, anton-sidelnikov commented on tests/integration/targets/dns_recordset_info/tasks/main.yaml
> +      register: dns_rs
you can add some checks for dns_rs

2021-06-08 07:54 UTC, anton-sidelnikov approved these changes

2021-06-08 08:05 UTC, gtema requested changes
Good, but:
- sort_dir, sort_key params are literally useless for Ansible modules, since there is absolutely no guarantee ansible will not screw ordering and in anyway user is able to sort it in any order
- since we need to upstream this module I propose we drop here support for zone_type completely. Instead if user (of OTC) is really interested in getting recordsets of a private zone he should first get ID of the private zone (through dns_zone_info module) and pass is here.

2021-06-08 08:05 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +  records:
should not be present. It is wrong here

2021-06-08 08:05 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +  sort_key:
useless in ansible modules

2021-06-08 08:05 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +  sort_dir:
useless in ansible modules

2021-06-08 08:05 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +        if self.params['zone_type']:
zone_type is not a supported parameter for listing recordsets (https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/dns/v2/recordset.py#L31)

2021-06-08 08:05 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +            ('recordset', not None,
it is not possible to query recordsets without knowing zone (API side of the story)

2021-06-08 11:55 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +    records:
dict is wrong, it must be list

2021-06-08 11:55 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +    records:
sample could be something like: [ "test1.open-telekom-cloud.com", ""test2.open-telekom-cloud.com"]

2021-06-08 14:39 UTC, Polina-Gubina submitted a review, later dismissed

2021-06-09 10:34 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +      - ID or name of the required zone.
If private zone is required, only id must be passed

2021-06-09 10:34 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +      - ID or name of the required zone.
By default public zone will be used

2021-06-11 08:03 UTC, anton-sidelnikov requested changes

2021-06-11 08:03 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +        type=dict(required=False, choices=['a', 'aaaa', 'mx', 'cname', 'txt', 'ns']),
we have more options

2021-06-11 08:06 UTC, SebastianGode requested changes

2021-06-11 08:06 UTC, SebastianGode commented on plugins/modules/dns_recordset_info.py
> +    module_kwargs = dict(
Check Mode support is missing.
While you don't need to change anything in code as the module doesn't change something the check_mode flag on ansible playbooks should not break it.

We already implemented it on all other info modules. Example here:
https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/lb_certificate_info.py#L84

2021-06-11 10:22 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +    module_kwargs = dict(
done

2021-06-11 10:26 UTC, SebastianGode submitted a review, later dismissed

2021-06-11 10:35 UTC, anton-sidelnikov submitted a review, later dismissed

2021-06-11 13:30 UTC, gtema requested changes

2021-06-11 13:30 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +      - Can be used only when zone is set.
This comment is not really corresponding to the code. The code works like:
- if zone is set we try to search recordsets in this zone
- otherwise we list all recordsets and filter them by name_or_id

2021-06-11 13:30 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +                    query['name'] = self.conn.dns.find_recordset(zone=query['zone'],
do we search recordset only to get it's name and start searching again? Instead this can be considered as "complete" and return the result

2021-06-11 13:30 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +  name_or_id:
it's a confusing name. Everywhere it is just "name"

2021-06-11 13:30 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +        for raw in self.conn.dns.recordsets(**query):
if zone was not set, but name_or_id (which should be renamed and then comment is not valid) is set - you pass unsupported query parameter.

2021-06-11 13:30 UTC, gtema commented on tests/integration/targets/dns_recordset_info/tasks/main.yaml
> +      register: recordsets
Please also test get_by_name (with and without zone)

2021-06-16 08:22 UTC, Polina-Gubina commented on test.yml
> +    - debug:
please delete it

2021-06-16 08:22 UTC, Polina-Gubina commented on test.yml
> +    - debug:
please delete it

2021-06-16 08:22 UTC, Polina-Gubina commented on tests/integration/targets/dns_recordset_info/tasks/main.yaml
> +        assert:
'assert' should be at the same level as 'name'

2021-06-16 08:24 UTC, Polina-Gubina commented on tests/integration/targets/dns_recordset_info/tasks/main.yaml
> +        assert:
rs.dns_recordset[0].name == recordset_random_name

2021-06-21 12:31 UTC, irina-pereiaslavskaia requested changes

2021-06-21 12:31 UTC, irina-pereiaslavskaia commented on test.yml
> +          - rsn | length > 0
Please, delete this file

2021-06-22 07:50 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +      returned. If private zone is required, only ID should be passed.
with backslash please

2021-06-22 07:50 UTC, Polina-Gubina commented on plugins/modules/dns_recordset_info.py
> +      - ID or name of the existing record set. if zone is set we try to search recordsets in this
same

2021-06-25 11:23 UTC, Polina-Gubina submitted a review, later dismissed

2021-06-30 08:09 UTC, anton-sidelnikov submitted a review, later dismissed

2021-10-01 09:51 UTC, irina-pereiaslavskaia submitted a review, later dismissed

2021-10-01 12:32 UTC, gtema approved these changes

2021-10-01 13:20 UTC, merged