antsibull-changelog - config&directories
opentelekomcloud/ansible-collection-cloud pull request #124
Opened 2021-07-08 10:59 UTC by SebastianGode

I added changelog directory with the config file. And I added fragments subdirectory. Any correctly created yaml file in the fragments directory will be picked up by `antsibull-changelog generate` and will be added to changelog.yaml in changelog folder and CHANGELOG.rst in main directory (can be adjusted)

2021-07-08 11:26 UTC, gtema requested changes
can you please also add a fragment: i.e. initializing changelog handling

2021-07-09 07:08 UTC, SebastianGode commented
> can you please also add a fragment: i.e. initializing changelog handling

done

2021-07-09 11:26 UTC, SebastianGode commented
recheck

2021-07-13 08:15 UTC, gtema approved these changes

2021-07-13 08:39 UTC, merged