New AS Instance module
opentelekomcloud/ansible-collection-cloud pull request #130
Opened 2021-08-04 13:00 UTC by irina-pereiaslavskaia

Add new module that helps to create/modify/delete AS Instances in AS Group.

2021-08-04 13:28 UTC, outcatcher requested changes

2021-08-04 13:28 UTC, outcatcher commented on plugins/modules/as_group.py
> +                sg_group = self.conn.network.find_security_group(
`sg_group` is basically `security group group` :)

2021-08-04 13:28 UTC, outcatcher commented on plugins/modules/as_group.py
> +                             instance.id]) == desire_instance_number):
Can be split into
```python
instances_with_id = [instance.id for instance in instances if instance.id]
...
if len(instances) == desire_instance_number == len(instances_with_id):
...
```

2021-08-05 08:17 UTC, anton-sidelnikov requested changes

2021-08-05 08:17 UTC, anton-sidelnikov commented on plugins/modules/as_instance.py
> +            elif action == 'remove':
it never happens

2021-08-05 08:39 UTC, anton-sidelnikov approved these changes

2021-08-05 08:40 UTC, irina-pereiaslavskaia commented on plugins/modules/as_instance.py
> +            elif action == 'remove':
It happens when we will work in check_mode.

2021-08-06 08:11 UTC, Polina-Gubina approved these changes

2021-08-06 08:14 UTC, outcatcher approved these changes

2021-08-06 08:44 UTC, merged