DDS Instance info module
opentelekomcloud/ansible-collection-cloud pull request #131
Opened 2021-08-13 14:38 UTC by YustinaKvr

1) Docs
2) Code
3) Integration tests
4) Ignore files

2021-08-13 15:49 UTC, anton-sidelnikov requested changes

2021-08-13 15:49 UTC, anton-sidelnikov commented on plugins/modules/dds_instance_info.py
> +      - Specifies the DB instance name.
wrong description

2021-08-13 15:49 UTC, anton-sidelnikov commented on tests/integration/targets/dds_instance_info/tasks/main.yaml
> +          - result.instance is defined
add endline

2021-08-17 13:20 UTC, lego963 requested changes

2021-08-17 13:20 UTC, lego963 commented on plugins/modules/dds_instance_info.py
> +          sample: "8635"
Is it `int` or `string`?

2021-08-18 11:39 UTC, anton-sidelnikov requested changes

2021-08-18 11:39 UTC, anton-sidelnikov commented on meta/runtime.yml
> +    - dds_instnce_info
typo here, should be: dds_instance_info

2021-08-18 11:43 UTC, anton-sidelnikov requested changes

2021-08-18 11:43 UTC, anton-sidelnikov commented on plugins/modules/dds_instance_info.py
> +        if instance:
maybe here if instance founded, we should exit with result?

2021-08-18 12:15 UTC, anton-sidelnikov commented on plugins/modules/dds_instance_info.py
> +                query['id'] = db_instance.id
dt = db_instance.to_dict()
dt.pop('location')
data.append(dt)        
self.exit(
            changed=False,
            instance=data
        )

2021-08-19 15:53 UTC, YustinaKvr commented on plugins/modules/dds_instance_info.py
> +          sample: "8635"
In docs https://docs.otc.t-systems.com/en-us/api/dds/dds_api_0023.html says it's int

2021-08-20 07:30 UTC, lego963 commented on plugins/modules/dds_instance_info.py
> +          sample: "8635"
If it's int it should be `8635` (without `"`)

2021-08-20 11:15 UTC, YustinaKvr commented on plugins/modules/dds_instance_info.py
> +        if instance:
Hmmm.. what if we put here an error message - in case of not found instance? I think it's pretty much logical solution:

            else:
                self.fail(changed=False, instances=[], msg="Instance not found")

2021-08-20 11:16 UTC, YustinaKvr commented on plugins/modules/dds_instance_info.py
> +          sample: "8635"
I deleted quotes, so now it's string accordingly docs

2021-08-23 11:25 UTC, anton-sidelnikov submitted a review, later dismissed

2021-08-23 12:16 UTC, lego963 submitted a review, later dismissed

2021-08-23 13:16 UTC, anton-sidelnikov approved these changes

2021-08-23 14:45 UTC, lego963 approved these changes

2021-08-30 08:38 UTC, merged