Css snapshot
opentelekomcloud/ansible-collection-cloud pull request #145
Opened 2021-11-08 07:14 UTC by enrrou

Resolves https://github.com/opentelekomcloud/ansible-collection-cloud/issues/143

2021-11-23 16:20 UTC, enrrou commented
recheck

2021-12-28 08:49 UTC, lego963 requested changes

2021-12-28 08:49 UTC, lego963 commented on meta/runtime.yml
> +    - css_snapshot
repeating

2021-12-28 08:49 UTC, lego963 commented on plugins/modules/css_snapshot.py
> +version_added: "0.9.0"
update version please

2021-12-28 08:49 UTC, lego963 commented on tests/sanity/ignore-2.9.txt
>  plugins/modules/css_snapshot_info.py validate-modules:missing-gplv3-license
repeating

2021-12-28 08:50 UTC, anton-sidelnikov requested changes

2021-12-28 08:50 UTC, anton-sidelnikov commented on tests/sanity/ignore-2.9.txt
> +plugins/modules/css_cluster_info.py validate-modules:missing-gplv3-license
duplicated entry

2021-12-28 08:50 UTC, anton-sidelnikov commented on plugins/modules/css_snapshot.py
> +version_added: "0.9.0"
0.10.0?

2021-12-28 10:01 UTC, anton-sidelnikov approved these changes

2021-12-28 10:26 UTC, lego963 approved these changes

2021-12-28 11:25 UTC, merged