vpc and dns_zone fixes
opentelekomcloud/ansible-collection-cloud pull request #177
Opened 2022-02-21 17:30 UTC by enrrou

May close issue (https://github.com/opentelekomcloud/ansible-collection-cloud/issues/176)

2022-02-22 08:03 UTC, anton-sidelnikov requested changes

2022-02-22 08:03 UTC, anton-sidelnikov commented on plugins/modules/dns_zone.py
> +            needs_update = True
i think here need to check diffs

2022-02-25 11:51 UTC, anton-sidelnikov approved these changes

2022-02-25 11:52 UTC, irina-pereiaslavskaia approved these changes

2022-02-25 11:53 UTC, outcatcher commented on plugins/modules/dns_zone.py
> +            else:
There is no need in `else` here, as exist is already done.

2022-02-25 11:57 UTC, outcatcher approved these changes

2022-02-25 12:02 UTC, lego963 approved these changes

2022-02-25 12:41 UTC, merged