Waf domain
opentelekomcloud/ansible-collection-cloud pull request #19
Opened 2020-09-02 11:29 UTC by anton-sidelnikov

WAF domain modules / Draft

2020-09-03 09:34 UTC, anton-sidelnikov commented
recheck

2020-09-04 13:05 UTC, gtema requested changes

2020-09-04 13:05 UTC, gtema commented on plugins/modules/waf_domain.py
> +    def _check_server_client_protocol(self, server: list):
function is not invoked, while it also hints, that module currently does not support check mode.
Please add into the tests invocation of the module with "check: true" param and fix the code correspondingly.
Idea is that in check mode module should say, whether it will do changes (create/delete/update) without really doing that.

2020-09-05 10:39 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +  server:
added

2020-09-05 10:48 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +    def _check_server_client_protocol(self, server: list):
done

2020-09-05 10:49 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +    server: [
done

2020-09-05 12:09 UTC, gtema requested changes
The check mode is currently not very correct, see comments in the code.
And please also add invocation with check mode from the integration test. I know we currently have not done this everywhere else properly, but let's start doing that

2020-09-05 12:09 UTC, gtema commented on plugins/modules/waf_domain.py
> +    def _check_server_client_protocol(self, server: list):
not precisely. Now check mode is not considering update

2020-09-05 12:09 UTC, gtema commented on plugins/modules/waf_domain.py
> +        if self.ansible.check_mode:
I would perhaps remove it here completely and instead before each modification call add this

2020-09-05 12:09 UTC, gtema commented on plugins/modules/waf_domain.py
> +                self.conn.waf.delete_domain(domain)
so here check: if check: return else: do

2020-09-05 12:09 UTC, gtema commented on plugins/modules/waf_domain.py
> +                domain = self.conn.waf.update_domain(domain, **mquery)
here as well if check: return True else: do

2020-09-05 12:09 UTC, gtema commented on plugins/modules/waf_domain.py
> +            domain = self.conn.waf.create_domain(**query)
and finally here
if check: return True else: do

2020-09-07 07:48 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +    def _check_server_client_protocol(self, server: list):
done

2020-09-07 07:50 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +            domain = self.conn.waf.create_domain(**query)
ok

2020-09-07 07:50 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +                domain = self.conn.waf.update_domain(domain, **mquery)
ok

2020-09-07 07:50 UTC, anton-sidelnikov commented on plugins/modules/waf_domain.py
> +                self.conn.waf.delete_domain(domain)
ok

2020-09-07 08:24 UTC, gtema requested changes
just a small remaining correction and good to go

2020-09-07 08:24 UTC, gtema commented on plugins/modules/waf_domain.py
> +                self.conn.waf.delete_domain(domain)
I would rather suggest here to simply return 
```
self.exit_json(changed=True)
```

You anyway is sure here, that we will drop it, no need to call evaluation again

2020-09-07 08:24 UTC, gtema commented on plugins/modules/waf_domain.py
> +                domain = self.conn.waf.update_domain(domain, **mquery)
and also here - just "changed=True"

2020-09-07 08:24 UTC, gtema commented on plugins/modules/waf_domain.py
> +            domain = self.conn.waf.create_domain(**query)
and here

2020-09-07 08:24 UTC, gtema commented on tests/integration/targets/waf_domain/tasks/main.yaml
> +      check_mode: yes
cool, but please add also assert "is changed" (or whatever Ansible pretends to return in check mode) to know how it is evaluated

2020-09-07 09:48 UTC, gtema approved these changes

2020-09-07 09:54 UTC, merged