Modules examples
opentelekomcloud/ansible-collection-cloud pull request #198
Opened 2022-05-27 12:15 UTC by YustinaKvr

1) Base operations with some infrastructure entities with short explanation and tips

2022-06-13 08:36 UTC, gtema commented
recheck

2022-07-08 09:08 UTC, anton-sidelnikov commented on doc/examples/3_autoscaling.yaml
> +    scaling_instances: ["{{ ecs1.server.id }}", "{{ ecs2.server.id }}"]
scaling_instances: 
 - "{{ ecs1.server.id }}"
 - "{{ ecs2.server.id }}"

2022-07-08 09:22 UTC, anton-sidelnikov commented on doc/examples/5_cce_cluster.yaml
> +  opentelekomcloud.cloud.cce_cluster:
add version

2022-07-08 09:23 UTC, anton-sidelnikov commented on doc/examples/5_cce_cluster.yaml
> +  opentelekomcloud.cloud.cce_cluster:
and more parameters

2022-07-08 09:26 UTC, anton-sidelnikov commented on doc/examples/5_cce_cluster.yaml
> +        cmk_id: ""
remove

2022-07-08 09:27 UTC, anton-sidelnikov commented on doc/examples/5_cce_cluster.yaml
> +        cmk_id: ""
or add additional example with cmk_id

2022-07-08 09:28 UTC, anton-sidelnikov commented on doc/examples/5_cce_cluster.yaml
> +    scale_down_cooldown_time: 5
remove

2022-07-08 09:37 UTC, anton-sidelnikov commented on doc/examples/6_loadbalancer.yaml
> +    admin_state_up: True
remove, this is constant value

2022-07-08 09:37 UTC, anton-sidelnikov commented on doc/examples/6_loadbalancer.yaml
> +    admin_state_up: True
rm

2022-07-29 10:49 UTC, anton-sidelnikov requested changes

2022-07-29 10:49 UTC, anton-sidelnikov commented on doc/examples/1_initial_infra.yaml
> +#      register: router
uncomment pls

2022-07-29 10:52 UTC, anton-sidelnikov commented on doc/examples/10_relation_database.yaml
> +# moment of creating RDS instance.
add comment about cmk creation

2022-07-29 11:06 UTC, anton-sidelnikov requested changes

2022-07-29 11:06 UTC, anton-sidelnikov commented on doc/examples/8_monitoring.yaml
> +# taken from API reference. SMN topic here has been created beforehand.
add url to namespaces info

2022-07-29 11:06 UTC, anton-sidelnikov commented on doc/examples/9_cloud_search.yaml
> +# created beforehand. Please pay attention that backup strategy is setting up also in this module.
add comment about cmk creation

2022-07-29 12:53 UTC, YustinaKvr commented on doc/examples/1_initial_infra.yaml
> +#      register: router
It's special section, contains examples using native OpenStack modules, to let users understand mismatches in entyties naming

2022-07-30 09:47 UTC, anton-sidelnikov approved these changes

2022-08-01 08:06 UTC, vladimirvshivkov approved these changes

2022-08-01 08:44 UTC, merged