cbr backup modules
opentelekomcloud/ansible-collection-cloud pull request #201
Opened 2022-06-09 21:25 UTC by Polina-Gubina

2022-07-25 13:27 UTC, vladimirvshivkov approved these changes

2022-07-25 15:25 UTC, anton-sidelnikov requested changes

2022-07-25 15:25 UTC, anton-sidelnikov commented on plugins/modules/cbr_restore_point.py
> +  vault:
please sort parameters alphabetically or by majority

2022-07-25 15:25 UTC, anton-sidelnikov commented on plugins/modules/cbr_restore_point.py
> +  vault:
in all modules

2022-07-25 19:07 UTC, Polina-Gubina commented on plugins/modules/cbr_restore_point.py
> +  vault:
all parametrs are sorted alphabetically but vault is first because it is madatory paramete
r

2022-07-26 06:50 UTC, anton-sidelnikov approved these changes

2022-07-27 07:02 UTC, vladimirvshivkov commented
regate

2022-07-27 07:21 UTC, merged