vault module
opentelekomcloud/ansible-collection-cloud pull request #204
Opened 2022-06-30 18:53 UTC by Polina-Gubina

2022-07-13 12:03 UTC, vladimirvshivkov requested changes

2022-07-13 12:03 UTC, vladimirvshivkov commented on plugins/modules/cbr_vault.py
> +                if self.params['billing']['size'] != vault['billing']['size']:
no need for double ifs, leave only  `if self.params['billing']['size'] != vault['billing']['size']:`

2022-07-13 12:21 UTC, vladimirvshivkov commented on plugins/modules/cbr_vault.py
> +    description: AS groups object.
maybe vault object?

2022-07-13 15:14 UTC, anton-sidelnikov commented on plugins/modules/cbr_vault.py
> +      - Used for modifying.
we do not modifying names in modules

2022-07-13 15:26 UTC, anton-sidelnikov requested changes

2022-07-13 15:26 UTC, anton-sidelnikov commented on plugins/modules/cbr_vault.py
> +            self.fail_json('vault not found')
add vault id or name in message

2022-07-13 15:26 UTC, anton-sidelnikov commented on plugins/modules/cbr_vault.py
> +        if state == 'absent':
add some message or just remove this

2022-07-13 15:26 UTC, anton-sidelnikov commented on tests/integration/targets/cbr/tasks/main.yaml
> +---
do not run this test in suite, add alias with disabled state

2022-07-15 13:46 UTC, anton-sidelnikov commented on tests/integration/targets/cbr/aliases
> +disabled
add empty line

2022-07-18 08:03 UTC, anton-sidelnikov approved these changes

2022-07-18 08:52 UTC, vladimirvshivkov requested changes

2022-07-18 08:52 UTC, vladimirvshivkov commented on plugins/modules/cbr_vault.py
> +    description: AS groups object.
unchanged

2022-07-18 09:08 UTC, vladimirvshivkov approved these changes

2022-07-18 09:36 UTC, merged