cbr policy module
opentelekomcloud/ansible-collection-cloud pull request #213
Opened 2022-07-29 07:45 UTC by Polina-Gubina

cbr policy module

2022-08-05 13:55 UTC, anton-sidelnikov requested changes

2022-08-05 13:55 UTC, anton-sidelnikov commented on plugins/modules/cbr_policy.py
> +        query['trigger']['properties']['pattern'] = []
just define dict with this keys

2022-08-05 13:55 UTC, anton-sidelnikov commented on tests/integration/targets/cbr/tasks/main.yaml
> +        name: "{{ (vault_name) }}"
why variables in ()?

2022-08-05 13:55 UTC, anton-sidelnikov commented on tests/integration/targets/cbr/tasks/main.yaml
> +        name: "{{ (vault_name) }}"
and below

2022-10-21 09:06 UTC, anton-sidelnikov submitted a review, later dismissed

2022-10-21 09:19 UTC, hadoopch commented
Hi Anton, i just tested the module.  KeyError: 'properties' error vanished.   
Thank you.   Now i can automate my backup.
In my tests i saw the module always ends with Changed. Also in the second run

2022-10-21 09:42 UTC, anton-sidelnikov commented
> Hi Anton, i just tested the module. KeyError: 'properties' error vanished. Thank you. Now i can automate my backup. In my tests i saw the module always ends with Changed. Also in the second run

Hello, working on it, @Polina-Gubina will fix modules

2022-10-21 12:13 UTC, Polina-Gubina commented
> Hi Anton, i just tested the module. KeyError: 'properties' error vanished. Thank you. Now i can automate my backup. In my tests i saw the module always ends with Changed. Also in the second run

2022-11-11 11:24 UTC, gtema requested changes
please add the module into the docs as well

2022-11-11 11:24 UTC, gtema commented on plugins/modules/cbr_policy.py
> +                self.exit_json(changed=True)
in check mode we should also return objects themselves

2022-11-11 11:24 UTC, gtema commented on plugins/modules/cbr_policy.py
> +            if not self.params['pattern']:
we could achieve that by making pattern mandatory with state="present"

2022-11-30 15:29 UTC, gtema requested changes

2022-12-06 17:40 UTC, anton-sidelnikov commented on plugins/modules/cbr_policy.py
> +        pattern=dict(type='list', required=False, elements='str'),
What if make pattern list of dicts?
cbr_policy:
  name: ..
  pattern:
    - FREQ: ..
      BYDAY: ..
      BYHOUR: ..
      BYMINUTE ..

For user perspective it can be more readable

2022-12-14 16:11 UTC, anton-sidelnikov approved these changes

2023-01-10 10:35 UTC, anton-sidelnikov commented on plugins/modules/cbr_policy.py
> +        query['trigger']['properties']['pattern'] = self.params['pattern']
trigger = {
  properties = {
    pattern = {}
  },
}

2023-01-11 11:54 UTC, anton-sidelnikov approved these changes

2023-03-02 11:14 UTC, gtema approved these changes

2023-03-02 11:36 UTC, merged