CSS cluster create backup strategy fix
opentelekomcloud/ansible-collection-cloud pull request #218
Opened 2022-08-03 10:48 UTC by vladimirvshivkov

2022-08-08 14:41 UTC, YustinaKvr submitted a review, later dismissed

2022-08-08 15:17 UTC, anton-sidelnikov requested changes

2022-08-08 15:17 UTC, anton-sidelnikov commented on tests/integration/targets/dms/aliases
> +disabled
Why disabled?

2022-08-08 15:17 UTC, anton-sidelnikov commented on plugins/modules/css_cluster.py
> +            keepday=dict(type='int'),
keepday has a range of values, maybe check it inside code?

2022-08-09 06:44 UTC, vladimirvshivkov commented on tests/integration/targets/dms/aliases
> +disabled
@vladimirvshivkov
[Service DMS is currently unavailable](https://github.com/opentelekomcloud/ansible-collection-cloud/pull/218/commits/e4d3d4248162f1583b5938f29cc95cc2cd7a13e1)

2022-08-09 06:51 UTC, vladimirvshivkov commented on tests/integration/targets/dms/aliases
> +disabled
DMS service is shut down

2022-08-09 06:51 UTC, vladimirvshivkov commented on plugins/modules/css_cluster.py
> +            keepday=dict(type='int'),
ok

2022-08-09 18:28 UTC, anton-sidelnikov requested changes

2022-08-09 18:28 UTC, anton-sidelnikov commented on plugins/modules/css_cluster.py
> +                    if self.params['backup_strategy']['keepday'] in range(1, 90):
is it possible to set more that 90 if you, check the range inside parameters section?

2022-08-10 05:14 UTC, vladimirvshivkov commented on plugins/modules/css_cluster.py
> +                    if self.params['backup_strategy']['keepday'] in range(1, 90):
checking range inside argument spec is not working

2022-08-10 05:15 UTC, vladimirvshivkov commented on plugins/modules/css_cluster.py
> +                    if self.params['backup_strategy']['keepday'] in range(1, 90):
it just passing through

2022-08-11 19:52 UTC, anton-sidelnikov approved these changes

2022-08-12 08:13 UTC, vladimirvshivkov commented
recheck

2022-08-12 09:26 UTC, Polina-Gubina approved these changes

2022-08-12 09:44 UTC, merged