NAT info modules gateway, snat, dnat
opentelekomcloud/ansible-collection-cloud pull request #22
Opened 2020-09-02 12:56 UTC by tischrei

2020-09-02 14:02 UTC, gtema requested changes

2020-09-02 14:02 UTC, gtema commented on plugins/modules/nat_snat_info.py
> +        for raw in self.conn.nat.snat_rules():
and here as well

2020-09-02 14:02 UTC, gtema commented on plugins/modules/nat_snat_info.py
> +            snat_list=data
nat_snat_rules please

2020-09-02 14:02 UTC, gtema commented on plugins/modules/rds_flavor_info.py
> -            sample: "10.0"
doesn't belong into this PR. In future please create separate PR for unrelated issues

2020-09-02 14:02 UTC, gtema commented on tests/sanity/ignore-2.9.txt
> -plugins/modules/loadbalancer_info.py validate-modules:missing-gplv3-license
and why you drop loadbalancer_info?

2020-09-04 14:39 UTC, tischrei commented
Reworked everthing.

2020-09-04 15:42 UTC, tischrei commented on plugins/modules/nat_gateway_info.py
> +    choices: ["1", "2", "3", "4"]
it is expected as string and not as int

2020-09-17 09:50 UTC, tischrei commented
recheck

2020-09-17 13:17 UTC, gtema approved these changes

2020-09-17 13:40 UTC, merged