Loadbalancer module
opentelekomcloud/ansible-collection-cloud pull request #24
Opened 2020-09-09 09:49 UTC by anton-sidelnikov

slightly reworked
added integration test

2020-09-14 13:06 UTC, anton-sidelnikov commented
@gtema somehow in zuul always failing TASK [loadbalancer : Create Router for ELB], can you look at that? In 447 integration test passed

2020-09-17 14:52 UTC, gtema requested changes
would you please generate random name for the integration test to avoid conflicts (what was reason for previous failures). Example is in other scenarios

2020-09-17 15:44 UTC, gtema commented on tests/integration/targets/loadbalancer/tasks/main.yaml
> +        network_name: "{{ ( prefix + '_my_test_network_lb') }}"
please as a suffix also use useful name to understand where orphans are coming from (i.e. acc-lb - AnsibleCollectionCloud-LoadBalancer)

2020-09-17 15:44 UTC, gtema commented on tests/integration/targets/loadbalancer/tasks/main.yaml
> +          - res.otc_loadbalancers is defined
please in the module rename otc_loadbalancers output to simply loadbalancers

2020-09-18 16:40 UTC, gtema approved these changes

2020-09-21 07:10 UTC, anton-sidelnikov commented
regate

2020-09-21 07:33 UTC, anton-sidelnikov commented
regate

2020-09-21 09:40 UTC, gtema commented
regate

2020-09-21 12:18 UTC, merged