CSS info refactor
opentelekomcloud/ansible-collection-cloud pull request #256
Opened 2023-02-02 17:58 UTC by vladimirvshivkov

simplified info module

2023-02-09 15:09 UTC, vladimirvshivkov commented
idea is to adopt SDK 1.0 and AOC 2.0

2023-02-10 10:43 UTC, anton-sidelnikov requested changes

2023-02-10 10:43 UTC, anton-sidelnikov commented on plugins/modules/dns_zone_info.py
> +version_added: "0.1.2"
0.13.1

2023-02-10 10:43 UTC, anton-sidelnikov commented on plugins/modules/dns_zone_info.py
> +short_description: Get DNS PTR Records
wrong description?

2023-02-10 10:43 UTC, anton-sidelnikov commented on plugins/modules/dns_zone_info.py
> +    - Get DNS PTR Records from the OTC.
here PTR

2023-02-10 12:26 UTC, Polina-Gubina submitted a review, later dismissed

2023-02-10 13:40 UTC, Polina-Gubina commented on plugins/modules/css_cluster_info.py
> +        css_clusters = self.conn.css.find_cluster(**kwargs)
what if name is not set and user want to get list by some filter?

2023-02-10 14:57 UTC, Polina-Gubina approved these changes

2023-02-13 10:17 UTC, anton-sidelnikov approved these changes

2023-02-13 10:32 UTC, merged