vpc peering info module
opentelekomcloud/ansible-collection-cloud pull request #27
Opened 2020-09-13 21:27 UTC by Polina-Gubina

2020-09-14 12:16 UTC, gtema requested changes

2020-09-14 12:16 UTC, gtema commented on plugins/modules/vpc_peering_info.py
> +    choices: [PENDING_ACCEPTANCE, REJECTED, EXPIRED, DELETED, ACTIVE]
please use lowercase for the values

2020-09-14 12:16 UTC, gtema commented on plugins/modules/vpc_peering_info.py
> +        tenant_id_filter = self.params['tenant_id']
we don't use tenant_id, but the project_id instead all over the code

2020-09-14 12:16 UTC, gtema commented on plugins/modules/vpc_peering_info.py
> +        vpc_id_filter = self.params['vpc_id']
and this one is router_id

2020-09-14 16:31 UTC, Polina-Gubina commented on plugins/modules/vpc_peering_info.py
> +    choices: [PENDING_ACCEPTANCE, REJECTED, EXPIRED, DELETED, ACTIVE]
but response is in uppercase, so when I use lowercase  this filter condition doesn't work

2020-09-14 16:36 UTC, Polina-Gubina commented on plugins/modules/vpc_peering_info.py
> +    choices: [PENDING_ACCEPTANCE, REJECTED, EXPIRED, DELETED, ACTIVE]
or do you mean something else?

2020-09-15 07:53 UTC, gtema commented on plugins/modules/vpc_peering_info.py
> +    choices: [PENDING_ACCEPTANCE, REJECTED, EXPIRED, DELETED, ACTIVE]
you accept them in lowercase and convert to upper case when invoking API

2020-09-15 16:16 UTC, gtema approved these changes

2020-09-15 16:38 UTC, merged