sfs turbo module
opentelekomcloud/ansible-collection-cloud pull request #274
Opened 2023-05-24 20:13 UTC by Polina-Gubina

2023-06-14 13:11 UTC, vladimirvshivkov requested changes

2023-06-14 13:11 UTC, vladimirvshivkov commented on plugins/modules/sfsturbo_share_action.py
> +- name: Extend capacity vpc
not relevant to sfs

2023-06-14 13:11 UTC, vladimirvshivkov commented on plugins/modules/sfsturbo_share_action.py
> +- name: Change security group
also here

2023-06-14 13:11 UTC, vladimirvshivkov commented on plugins/modules/sfsturbo_share_action.py
> +module: sfsturbo_share_action
not clear what this module does

2023-06-14 13:11 UTC, vladimirvshivkov commented on meta/runtime.yml
> +    - sfsturbo
here should be listed all new modules

2023-06-14 13:11 UTC, vladimirvshivkov commented on tests/integration/targets/sfsturbo/aliases
> +sfsturbo/group1
new line needed

2023-06-15 08:21 UTC, artem-lifshits approved these changes

2023-06-15 09:25 UTC, anton-sidelnikov requested changes

2023-06-15 09:25 UTC, anton-sidelnikov commented on plugins/modules/sfsturbo_share_action.py
> +version_added: "0.10.0"
again should be next from latest 0.15.0

2023-06-15 09:25 UTC, anton-sidelnikov commented on plugins/modules/sfsturbo_share_action.py
> +            if int(float(share.avail_capacity)) != self.params['new_size']:
why float here? and then int conversion, loooks strange

2023-06-15 09:25 UTC, anton-sidelnikov commented on plugins/modules/sfsturbo_share_action.py
> +            if int(float(share.avail_capacity)) != self.params['new_size']:
share.avail_capacity is a string  or what?

2023-06-16 09:02 UTC, anton-sidelnikov requested changes

2023-06-16 09:02 UTC, anton-sidelnikov commented on plugins/modules/sfsturbo_share.py
> +            if attributes['size'] != int(float(resource['size'])):
check please on bigger value

2023-06-16 11:27 UTC, anton-sidelnikov approved these changes

2023-06-19 11:01 UTC, anton-sidelnikov approved these changes

2023-06-19 11:03 UTC, artem-lifshits approved these changes

2023-06-19 11:03 UTC, vladimirvshivkov approved these changes

2023-06-19 11:18 UTC, merged