vlb loadbalancer info module
opentelekomcloud/ansible-collection-cloud pull request #285
Opened 2023-07-19 13:34 UTC by Polina-Gubina

2023-07-20 09:39 UTC, anton-sidelnikov requested changes

2023-07-20 09:39 UTC, anton-sidelnikov commented on meta/runtime.yml
> +    - vlb_loadbalancer_info
lets call it dlb_loadbalancer_info (as dedicated load balancer)

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  vip_subnet_cidr_id:
subnet_id

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  vip_address:
ip_address

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  vip_port_id:
port_id

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  availability_zone_list:
availability_zones

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  member_device_id:
member_id

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +  elb_virsubnet_type:
subnet_type

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +    description:
check description: loadbalancers -> contains -> elb_virsubnet_type -> description -> 2\n  str type expected (type=type_error.str)']:plugin_name=opentelekomcloud.cloud.vlb_loadbalancer_info:plugin_type=module|opentelekomcloud.cloud.vlb_loadbalancer_info did not return correct RETURN or EXAMPLES

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +      description:
try to rename this field also in response to: network_ids

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +      description:
and here: loadbalancers -> contains -> elb_virsubnet_type -> description -> 2\n  str type expected (type=type_error.str)']:plugin_name=opentelekomcloud.cloud.vlb_loadbalancer_info:plugin_type=module|opentelekomcloud.cloud.vlb_loadbalancer_info did not return correct RETURN or EXAMPLES

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +    elb_virsubnet_type:
subnet_type

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +    vip_port_id:
try to rename this field also in response to: port_id

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +    vip_subnet_cidr_id:
try to rename this field also in response to: subnet_id

2023-07-20 09:39 UTC, anton-sidelnikov commented on plugins/modules/vlb_loadbalancer_info.py
> +    vip_address:
try to rename this field also in response to: ip_address

2023-07-20 09:41 UTC, anton-sidelnikov commented on meta/runtime.yml
> +    - vlb_loadbalancer_info
or better even call it simply loadbalancer_info, because it will be unified for both type of loadbalancers

2023-07-20 09:44 UTC, anton-sidelnikov commented
https://github.com/opentelekomcloud/ansible-collection-cloud/blob/main/tests/sanity/ignore.txt also add your module here

2023-07-21 10:45 UTC, artem-lifshits submitted a review, later dismissed

2023-07-21 12:32 UTC, anton-sidelnikov requested changes

2023-07-21 12:32 UTC, anton-sidelnikov commented on plugins/modules/loadbalancer_v3_info.py
> +  elb_virsubnet_type:
subnet_type

2023-07-21 12:32 UTC, anton-sidelnikov commented on plugins/modules/loadbalancer_v3_info.py
> +    elb_virsubnet_ids:
subnet_ids

2023-07-21 12:32 UTC, anton-sidelnikov commented on plugins/modules/loadbalancer_v3_info.py
> +    elb_virsubnet_type:
subnet_type

2023-07-21 13:50 UTC, anton-sidelnikov approved these changes

2023-07-21 13:51 UTC, artem-lifshits approved these changes

2023-07-24 10:29 UTC, merged