Vpc peering
opentelekomcloud/ansible-collection-cloud pull request #30
Opened 2020-09-22 21:35 UTC by Polina-Gubina

Creation, updating, deleting of a vpc peering

2020-09-23 19:52 UTC, Polina-Gubina commented
recheck

2020-09-25 17:45 UTC, gtema requested changes

2020-09-25 17:45 UTC, gtema commented on plugins/modules/vpc_peering.py
> +        try:
this construct you should be able to achieve by passing "find_peering(name, ignore_missing=True)" without try/catch

2020-09-25 17:45 UTC, gtema commented on plugins/modules/vpc_peering.py
> +                updated_vpc_peering = self.conn.vpc.update_peering(vpc_peering, **attrs)
you do update, but do not consider this actions in the _system_state_change. So check mode will return "changed=False", but real run will do the change

2020-09-25 17:45 UTC, gtema commented on tests/integration/targets/vpc_peering/tasks/main.yaml
> +      os_network:
we need to use FQCN for openstack modules (openstack.cloud.network). I wonder the test is not failing, but in the long run for sure it will stop working some time

2020-11-11 07:27 UTC, Polina-Gubina commented
recheck

2020-11-11 07:41 UTC, Polina-Gubina commented
recheck

2020-11-11 10:07 UTC, tischrei requested changes

2020-11-11 10:07 UTC, tischrei commented on plugins/modules/vpc_peering.py
> +- vpc_peering:
please use opentelekomcloud.cloud.vpc_peering in alle examples

2020-11-11 10:07 UTC, tischrei commented on plugins/modules/vpc_peering.py
> +version_added: "0.0.3"
please use latest tag in version

2020-11-11 10:07 UTC, tischrei commented on plugins/modules/vpc_peering.py
> +id:
please check your return values. it starts with "vpc_peering"

2020-11-11 10:07 UTC, tischrei commented on tests/integration/targets/vpc_peering/tasks/main.yaml
> +    - block:
use ignore_errors: yes to avoid abort of the cleanup block.

2020-11-12 14:09 UTC, anton-sidelnikov commented on plugins/modules/vpc_peering.py
> +            sample: "2020-09-13T20:38:02"
use here 2 spaces instead of 4

2020-11-13 07:04 UTC, anton-sidelnikov commented on plugins/modules/vpc_peering.py
> +          sample: "2020-09-13T20:38:02"
use 2 spaces instead of 4

2020-11-13 12:51 UTC, Polina-Gubina commented
recheck

2020-11-16 10:22 UTC, anton-sidelnikov approved these changes

2020-11-16 13:14 UTC, tischrei approved these changes

2020-11-19 09:30 UTC, gtema approved these changes

2020-11-19 09:43 UTC, merged