lb_member modules
opentelekomcloud/ansible-collection-cloud pull request #33
Opened 2020-09-28 11:01 UTC by anton-sidelnikov

lb_member_info added

2020-10-13 11:29 UTC, tischrei requested changes

2020-10-13 11:29 UTC, tischrei commented on plugins/modules/lb_member.py
> +lb_member:
lb_member -> member

2020-10-13 11:29 UTC, tischrei commented on plugins/modules/lb_member.py
> +      - Specifies the backend server group name.
it is not the "backend server group name" it is "backend server name"

2020-10-13 11:29 UTC, tischrei commented on plugins/modules/lb_member.py
> +        name=dict(required=True),
name is not required by API

2020-10-13 11:29 UTC, tischrei commented on plugins/modules/lb_healthmonitor_info.py
> +    argument_spec = dict(
Further query parameters are missing:
'delay', 'max_retries', 'timeout','adminstate_up', project_id

2020-10-14 07:52 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor_info.py
> +lb_healthmonitor_info:
but in openstack modules all load balancer modules has lb prefix, and other modules like pool and listener, I'm did in this way of naming

2020-10-14 07:52 UTC, anton-sidelnikov commented on tests/integration/targets/lb_infos/tasks/main.yaml
> +    lb_healthmonitor_info:
done

2020-10-14 08:27 UTC, anton-sidelnikov commented on plugins/modules/lb_member_info.py
> +    argument_spec = dict(
done

2020-10-14 08:27 UTC, anton-sidelnikov commented on plugins/modules/lb_member.py
> +lb_member:
done

2020-10-14 08:27 UTC, anton-sidelnikov commented on plugins/modules/lb_member.py
> +        name=dict(required=True),
done

2020-10-14 08:27 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor_info.py
> +    argument_spec = dict(
done

2020-10-14 08:28 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor.py
> +# Update a health check to backed server group in ELB.
done

2020-10-14 08:28 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor.py
> +# Add a health check to backed server group in ELB.
done

2020-10-14 08:28 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor.py
> +lb_healthmonitor:
same as in the previous comment

2020-10-14 09:30 UTC, tischrei commented on plugins/modules/lb_healthmonitor_info.py
> +lb_healthmonitor_info:
Hi Anton,

yes for the module naming this is correct. But you have named the return value with the same scheme. The return value corresponds with the value provided in the output which is in this case "healthmonitors". Otherwise user will not know that for instance a registered variable like "lb_health" has the parameter "lb_health.healthmonitors", they would expect "lb_health.lb_healthmonitor_info" instead which is not correct.

You can also check any corresponding openstack.cloud.* module where it is done this way e.g.:
https://opendev.org/openstack/ansible-collections-openstack/src/branch/master/plugins/modules/port_info.py#L58

2020-10-14 09:33 UTC, tischrei commented on plugins/modules/lb_healthmonitor.py
> +lb_healthmonitor:
the same mentioned as above, please check also: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#return-block

...where everything is described in detail.

2020-10-14 09:40 UTC, tischrei commented on plugins/modules/lb_member.py
> +lb_member:
lb_member is still lb_member, but the return value is "member"

2020-10-14 09:42 UTC, anton-sidelnikov commented on plugins/modules/lb_healthmonitor.py
> +lb_healthmonitor:
awww, you're right, my bad

2020-10-14 12:31 UTC, anton-sidelnikov commented on tests/integration/targets/loadbalancer/tasks/main.yaml
>          timeout: 600
i will fix it in another branch, and others bugs

2020-10-14 13:03 UTC, tischrei approved these changes

2020-10-14 13:12 UTC, merged