Adding DWS cluster info module
opentelekomcloud/ansible-collection-cloud pull request #341
Opened 2024-06-19 14:09 UTC by sattila1999

Created DWS cluster info module.

2024-06-19 14:39 UTC, vineet-pruthi approved these changes

2024-06-21 15:47 UTC, anton-sidelnikov requested changes
Intergation test?

2024-06-21 15:47 UTC, anton-sidelnikov commented on plugins/modules/dws_cluster_info.py
> +      enterprise_project_id:
this parameter doesn't work in otc, better to remove it

2024-06-25 07:25 UTC, sattila1999 commented on plugins/modules/dws_cluster_info.py
> +      enterprise_project_id:
Hi! The unused parameters are removed.

2024-06-25 08:52 UTC, anton-sidelnikov approved these changes

2024-06-25 09:03 UTC, merged