Adding mrs_cluster_info module
opentelekomcloud/ansible-collection-cloud pull request #344
Opened 2024-07-04 13:08 UTC by sattila1999

Adding mrs_cluster_info module.

2024-07-04 13:21 UTC, vineet-pruthi submitted a review, later dismissed

2024-07-04 13:42 UTC, anton-sidelnikov requested changes

2024-07-04 13:42 UTC, anton-sidelnikov commented on plugins/modules/mrs_cluster_info.py
> +version_added: "0.14.4"
version added reflects to tag which contains this module. So need to set next from latest, 0.14.5

2024-07-04 13:48 UTC, anton-sidelnikov requested changes

2024-07-04 13:48 UTC, anton-sidelnikov commented on plugins/modules/mrs_cluster_info.py
> +            mrs_clusters = [c.to_dict(computed=False) for c in raw]
.pop('location')?

2024-07-05 12:14 UTC, sattila1999 commented on plugins/modules/mrs_cluster_info.py
> +            mrs_clusters = [c.to_dict(computed=False) for c in raw]
resolved

2024-07-05 18:20 UTC, vineet-pruthi approved these changes

2024-07-08 08:36 UTC, anton-sidelnikov approved these changes

2024-07-08 08:51 UTC, merged