DeH info modules
opentelekomcloud/ansible-collection-cloud pull request #39
Opened 2020-10-01 13:52 UTC by tischrei

2020-10-01 13:54 UTC, tischrei commented
The UUIDs and other data aren't real values.

2020-10-26 08:49 UTC, gtema requested changes

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_host_info.py
> +- deh_host_info:
please use FQCN in examples

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_host_info.py
> +version_added: "0.0.1"
version is too old

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_host_type_info.py
> +version_added: "0.0.1"
version is too old

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_host_type_info.py
> +- deh_host_type_info:
FQCN

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_server_info.py
> +version_added: "0.0.1"
version is too old

2020-10-26 08:49 UTC, gtema commented on plugins/modules/deh_server_info.py
> +- deh_server_info:
FQCN

2020-10-26 10:31 UTC, tischrei commented on plugins/modules/deh_host_info.py
> +- deh_host_info:
done

2020-10-26 10:32 UTC, tischrei commented on plugins/modules/deh_host_info.py
> +version_added: "0.0.1"
I don't understand your "version procedere". For me: The first version is the first edit. After the thing is released and I change something, I edit the version. What do you expect?

2020-10-26 10:35 UTC, tischrei commented on plugins/modules/deh_host_type_info.py
> +version_added: "0.0.1"
done

2020-10-26 10:35 UTC, tischrei commented on plugins/modules/deh_host_type_info.py
> +- deh_host_type_info:
done

2020-10-26 10:35 UTC, tischrei commented on plugins/modules/deh_server_info.py
> +version_added: "0.0.1"
done

2020-10-26 10:35 UTC, gtema commented on plugins/modules/deh_host_info.py
> +version_added: "0.0.1"
This info is for users to be able to understand starting from which released version this module is available (when looking to docs, etc)

2020-10-26 10:35 UTC, tischrei commented on plugins/modules/deh_server_info.py
> +- deh_server_info:
done

2020-10-26 10:38 UTC, tischrei commented on plugins/modules/deh_host_info.py
> +version_added: "0.0.1"
Okidoki, I have changed the versions again according to our current label.

2020-10-27 10:37 UTC, tischrei commented
recheck

2020-10-27 10:55 UTC, tischrei commented
recheck

2020-10-27 11:21 UTC, tischrei commented
recheck

2020-11-03 11:48 UTC, tischrei commented
@gtema all changes are done, all other modules are added and integration tests are done.

2020-11-03 12:23 UTC, gtema approved these changes

2020-11-04 08:51 UTC, merged