DNS Info Modules
opentelekomcloud/ansible-collection-cloud pull request #40
Opened 2020-10-02 11:36 UTC by SebastianGode

2020-10-06 11:30 UTC, anton-sidelnikov commented on plugins/modules/dns_recordset_info.py
> +            i = i + 1
i think we don't need such complex logic in info modules, do filtering only by id or name

2020-10-26 09:02 UTC, gtema requested changes

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +            if self.params['create_at']:
honestly speaking I doubt in necessity in filtering on dates. Normal practice is to filter on whatever is supported by the API (plus basic name/id)

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_recordset_info.py
> +        while i < len(data):
and again - merge loops

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_zone_info.py
> +version_added: "0.0.1"
version is too old

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_zone_info.py
> +  created_at:
drop date filters

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_zone_info.py
> +            query['zone_type'] = self.params['zone_type']
lots of filters are already suported by API (https://docs.openstack.org/api-ref/dns/?expanded=list-floatingip-s-ptr-record-detail,list-recordsets-in-a-zone-detail,list-zones-detail#list-zones), please pass as much as possible into list

2020-10-26 09:02 UTC, gtema commented on plugins/modules/dns_zone_info.py
> +        while i < len(data):
same as above

2020-11-03 08:42 UTC, SebastianGode commented on plugins/modules/dns_floating_ip_info.py
> +  dns_floating_ip_info:
So something like 
`# Get Nameserver Info about a zone:
- name: Getting Info
  dns_floating_ip_info:
    description: "Test"
    ptrdname: "example.com"`

2020-11-03 09:22 UTC, SebastianGode commented on plugins/modules/dns_floating_ip_info.py
> +        while i < len(data):
Do you have an Idea how I can merge that into the previous loop?
And why is that bad? Those aren't double loops, the runtime should be still linear O(n).
@gtema

2020-11-03 09:25 UTC, SebastianGode commented on plugins/modules/dns_nameserver_info.py
> +version_added: "0.0.3"
FIxed

2020-11-03 09:25 UTC, SebastianGode commented on plugins/modules/dns_zone_info.py
> +version_added: "0.0.1"
Fixed

2020-11-03 09:29 UTC, SebastianGode commented on plugins/modules/dns_zone_info.py
> +            query['zone_type'] = self.params['zone_type']
@gtema I looked at our doc under https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62003.html and there nothing of that is written. WIll change that

2020-11-04 10:40 UTC, SebastianGode commented on plugins/modules/dns_recordset_info.py
> +            i = i + 1
Else filtering is not possible as the query doesn't accept any queries. 

Without filtering those modules wouldn't make sense at all

2020-11-10 17:03 UTC, opnmind commented on plugins/modules/dns_floating_ip_info.py
> +#!/usr/bin/python
Is this correct anymore? Normally I would suggest an shebang like this:

```py
#!/usr/bin/env python3
```
@gtema whats your opinion regarding the discussion about python2/python3 shebang's?

2020-11-10 17:24 UTC, opnmind commented on plugins/modules/dns_floating_ip_info.py
> +ptr_records:
Confusing yaml indention. Above you use 2 spaces and now 4 spaces.

2020-11-10 17:26 UTC, opnmind commented on plugins/modules/dns_nameserver_info.py
> +RETURN = '''
Same yaml indention here. 4 spaces instead of 2.

2020-11-10 17:28 UTC, opnmind commented on plugins/modules/dns_nameserver_info.py
> +            zi = self.conn.dns.find_zone(
I personally don't like short variables. I would prefer `dns_zone` as variable.

2020-11-10 17:29 UTC, opnmind commented on plugins/modules/dns_nameserver_info.py
> +        for raw in self.conn.dns.nameservers(**query):
`raw` could be `raw_nameserver`

2020-11-10 17:35 UTC, opnmind commented on plugins/modules/dns_nameserver_info.py
> +            dt = raw.to_dict()
Here also I would prefer long variable names:
```py
dt = raw.to_dict()
dt.pop('location')
data.append(dt)
```
to:
```py
tmp_data = raw_nameserver.to_dict() # or nameserver.to_dict()
tmp_data.pop('location')
data.append(tmp_data)
```

2020-11-11 08:46 UTC, SebastianGode commented on plugins/modules/dns_floating_ip_info.py
> +#!/usr/bin/python
@opnmind Typical it makes no difference in e.g. modern Ubuntu systems.
Python is an Link to Python3

To specify Python2.7 you would need to write Python2.7 there.

2020-11-11 08:53 UTC, SebastianGode commented on plugins/modules/dns_nameserver_info.py
> +            zi = self.conn.dns.find_zone(
@opnmind It really doesn't matter in those cases where I use those short vars as they aren't really used anymore than like 3lines below.

2020-11-11 08:54 UTC, SebastianGode commented on plugins/modules/dns_nameserver_info.py
> +        for raw in self.conn.dns.nameservers(**query):
@opnmind Same here, I need raw only for the 1 line below. A longer var makes no sense there

2020-11-11 14:23 UTC, tischrei commented on plugins/modules/dns_floating_ip_info.py
> +version_added: "0.1.2"
too old

2020-11-11 14:25 UTC, tischrei commented
functional test is missing.

2020-11-11 14:25 UTC, tischrei requested changes
pls add functional test or in combination with your other DNS PR which makes sense ;-).

2020-11-11 14:25 UTC, tischrei commented on plugins/modules/dns_nameserver_info.py
> +version_added: "0.1.2"
too old, too

2020-11-13 09:53 UTC, SebastianGode commented
Integration Tests are added :)

2020-11-19 09:14 UTC, SebastianGode commented
Don't merge this yet.
Merge DNS Modules first

2020-11-27 08:24 UTC, SebastianGode commented
recheck

2021-01-05 09:01 UTC, SebastianGode commented
recheck

2021-01-08 09:07 UTC, SebastianGode commented
recheck

2021-01-20 07:18 UTC, SebastianGode commented
recheck

2021-01-25 09:36 UTC, SebastianGode commented
recheck

2021-01-26 11:27 UTC, SebastianGode commented
recheck

2021-01-28 10:28 UTC, SebastianGode commented
recheck

2026-06-26 08:39 UTC, anton-sidelnikov commented
outdated

2026-06-26 08:39 UTC, closed without merging