Vpc route info
opentelekomcloud/ansible-collection-cloud pull request #42
Opened 2020-10-12 06:48 UTC by Polina-Gubina

2020-10-12 08:39 UTC, Polina-Gubina commented
recheck

2020-10-26 08:43 UTC, gtema submitted a review, later dismissed

2020-10-26 08:43 UTC, gtema commented on plugins/modules/vpc_route_info.py
> +  tenant_id:
this should be project_id

2020-10-26 08:43 UTC, gtema commented on plugins/modules/vpc_route_info.py
> +  vpc_id:
router_id

2020-10-26 08:43 UTC, gtema commented on plugins/modules/vpc_route_info.py
> +    vpc_id:
I think those are returned as router_id and project_id as well

2020-10-26 08:43 UTC, gtema commented on plugins/modules/vpc_route_info.py
> +            query['status'] = tenant_id_filter
I guess there is typo here - 'status' is definitely wrong

2020-10-26 08:43 UTC, gtema commented on plugins/modules/vpc_route_info.py
> +            query['project_id'] = vpc_id_filter
here also mixed

2020-10-26 17:00 UTC, Polina-Gubina commented
recheck

2020-10-26 20:27 UTC, Polina-Gubina commented
recheck

2020-10-27 07:04 UTC, Polina-Gubina commented
recheck

2020-10-27 07:54 UTC, Polina-Gubina commented
do not do recheck

2020-10-27 08:13 UTC, Polina-Gubina commented
recheck

2020-10-27 17:14 UTC, Polina-Gubina commented
recheck

2020-11-09 08:47 UTC, anton-sidelnikov commented on tests/integration/targets/vpc_route_info/tasks/main.yaml
> +          - vpc_routes.vpc_routes is defined
endline

2020-11-09 08:48 UTC, anton-sidelnikov approved these changes

2020-11-11 09:48 UTC, tischrei requested changes

2020-11-11 09:48 UTC, tischrei commented on plugins/modules/vpc_route_info.py
> +version_added: "0.0.2"
0.2.0 is it is mentioned in our tag

2020-11-11 09:52 UTC, tischrei approved these changes

2020-11-11 10:14 UTC, merged