Vpc route module
opentelekomcloud/ansible-collection-cloud pull request #43
Opened 2020-10-12 13:51 UTC by Polina-Gubina

2020-10-12 16:17 UTC, Polina-Gubina commented
recheck

2020-10-19 10:22 UTC, Polina-Gubina commented
Depends-On: opentelekomcloud/ansible-collection-cloud#{{30}}

2020-10-26 06:42 UTC, Polina-Gubina commented
recheck

2020-10-27 08:14 UTC, Polina-Gubina commented
recheck

2020-10-27 17:39 UTC, Polina-Gubina commented
recheck

2020-10-27 17:59 UTC, Polina-Gubina commented
Depends-On: #30

2020-10-30 11:24 UTC, Polina-Gubina commented
recheck

2020-10-30 11:40 UTC, Polina-Gubina commented
recheck

2020-11-03 13:58 UTC, Polina-Gubina commented
recheck

2020-11-09 08:55 UTC, anton-sidelnikov submitted a review, later dismissed

2020-11-11 14:08 UTC, tischrei commented
check for conflicts.

2020-11-11 14:09 UTC, tischrei commented on plugins/modules/vpc_route.py
> +version_added: "0.0.3"
version 0.2.0

2020-11-11 14:16 UTC, tischrei approved these changes

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +    - block:
ignore_errors: yes is missing

2020-11-11 14:16 UTC, tischrei commented on plugins/modules/vpc_route.py
> +- vpc_route:
pls provide full qualified cname opentelekomcloud.cloud.modulname

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +    vpc_peering:
complete module name is missing, so it fails for me.

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +      vpc_peering:
the same as above

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +      vpc_route:
module name

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +      vpc_route:
module name

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +      vpc_route:
module name

2020-11-11 14:16 UTC, tischrei commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +        vpc_peering:
module name

2020-11-11 14:18 UTC, tischrei requested changes
Please correct the comments

2020-11-11 14:23 UTC, anton-sidelnikov commented on plugins/modules/vpc_route.py
> +        sample: "6ysa5bac-0925-4d5b-add8-cb6667b8"
use 2 instead 4 spaces

2020-11-11 14:23 UTC, anton-sidelnikov commented on plugins/modules/vpc_route.py
> +        for raw in self.conn.vpc.routes(**query):
if raw null?

2020-11-12 17:04 UTC, Polina-Gubina commented
recheck

2020-11-13 13:32 UTC, anton-sidelnikov commented on tests/integration/targets/vpc_route/tasks/main.yaml
> +        ignore_errors: yes
you can remove that

2020-11-13 13:33 UTC, anton-sidelnikov requested changes
look at int test

2020-11-16 10:12 UTC, anton-sidelnikov submitted a review, later dismissed

2020-11-16 12:23 UTC, anton-sidelnikov approved these changes

2020-11-19 09:29 UTC, gtema approved these changes

2020-11-19 09:33 UTC, tischrei approved these changes

2020-11-19 09:48 UTC, merged