security_group_info module added which is missing in openstack.cloud.* collection
opentelekomcloud/ansible-collection-cloud pull request #53
Opened 2020-10-20 16:04 UTC by tischrei

2020-10-21 12:58 UTC, Polina-Gubina approved these changes

2020-10-26 09:09 UTC, gtema requested changes

2020-10-26 09:09 UTC, gtema commented on plugins/modules/security_group_info.py
> +version_added: "0.0.1"
version too old

2020-10-26 09:09 UTC, gtema commented on plugins/modules/security_group_info.py
> +  security_group:
best practice in openstack collection, which we follow, is to have attribute `name` as name or id

2020-10-26 09:09 UTC, gtema commented on plugins/modules/security_group_info.py
> +        if self.params['security_group']:
please compare with https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/waf_domain_info.py for name/id handling

2020-10-26 14:38 UTC, tischrei commented on plugins/modules/security_group_info.py
> +version_added: "0.0.1"
done

2020-10-26 15:40 UTC, tischrei commented
review changes finished.

2020-10-27 10:37 UTC, tischrei commented
recheck

2020-11-03 11:51 UTC, tischrei commented
pls recheck @gtema

2020-11-03 12:23 UTC, gtema approved these changes

2020-11-03 12:44 UTC, merged