Change README and add module descriptions
opentelekomcloud/ansible-collection-cloud pull request #54
Opened 2020-10-21 13:08 UTC by tischrei

2020-10-21 15:38 UTC, lego963 commented on README.md
> +- hosts: localhost
you can use \`\`\`yaml against \`\`\`bash for yaml files. Here is examples:
```yaml
- hosts: localhost
  tasks:
    - name: Get NAT gateway info
      opentelekomcloud.cloud.nat_gateway_info:
        cloud: otc
      register: gw
  
    - name: debug configs
      debug:
        var: gw.nat_gateways
```

```bash
- hosts: localhost
  tasks:
    - name: Get NAT gateway info
      opentelekomcloud.cloud.nat_gateway_info:
        cloud: otc
      register: gw
  
    - name: debug configs
      debug:
        var: gw.nat_gateways
```

2020-10-21 15:46 UTC, gtema requested changes
I am not sure about the way.
1) docs should be auto-generated and not manually
2) not sure publishing will work as should

2020-10-21 16:20 UTC, tischrei commented
> I am not sure about the way.
> 
> 1. docs should be auto-generated and not manually
> 2. not sure publishing will work as should

related to 1: These docs are auto-generated. We have to implement this in Zuul as well.
related to 2: I oriented at several collections which are using this procedere. So I thought this is a fast way to have those infos online. There is a much better solution: but I think we need someone who is the owner of our collection cloud. There are collections which are marked as "These are the collections with docs hosted on docs.ansible.com." which you can find here: https://docs.ansible.com/ansible/2.10/collections/index.html For these collections the modules are documented directly in Ansible Galaxy and this is clickable.

I used the way of VMware: https://galaxy.ansible.com/community/vmware to get something online as fast as possible.

2020-10-21 16:24 UTC, tischrei commented on README.md
> +- hosts: localhost
Thanks, I changed it.

2020-10-21 16:33 UTC, gtema commented
> related to 2: I oriented at several collections which are using this procedere. So I thought this is a fast way to have those infos online. There is a much better solution: but I think we need someone who is the owner of our collection cloud. There are collections which are marked as "These are the collections with docs hosted on docs.ansible.com." which you can find here: https://docs.ansible.com/ansible/2.10/collections/index.html For these collections the modules are documented directly in Ansible Galaxy and this is clickable.
> 
> I used the way of VMware: https://galaxy.ansible.com/community/vmware to get something online as fast as possible.

This is unfortunately absolutely not documented by Ansible. OpenStack collection is listed there while not having docs in source, on the other side if on the page you refer you switch to the "devel" version - it is gone. So, there is no documented instruction of Ansible Galaxy what to do with docs, so just generating them from source and keeping __in__ the source is not really a correct and future-proof way.

2020-10-21 16:42 UTC, tischrei commented
> This is unfortunately absolutely not documented by Ansible. OpenStack collection is listed there while not having docs in source, on the other side if on the page you refer you switch to the "devel" version - it is gone. So, there is no documented instruction of Ansible Galaxy what to do with docs, so just generating them from source and keeping **in** the source is not really a correct and future-proof way.

Yes I know, let us start with "my" solution and meanwhile I try to get infos out of the Ansible IRC or somewhere else, oki?

2020-10-21 17:33 UTC, gtema commented
> Yes I know, let us start with "my" solution and meanwhile I try to get infos out of the Ansible IRC or somewhere else, oki?

- CI is not really capable to auto-generate doc and commit it into the source. Generating docs and publish them somewhere - no problem, but not add it into the sourcecode.
- Until this is automat-able any change in the module must include "manual" update in the doc - not practical. It will cause mismatches.
- I guess in the next future we will not achieve docs under docs.galaxy.com. It tend only to include documentation for collections underneath ansible-collections NS (or only what is part of ansible-base), which we are not.

2020-10-26 10:45 UTC, tischrei commented
Okay, I removed everything which was not accepted by Artem in leave the README changes to provide a better "get started".

2020-10-26 10:46 UTC, lego963 submitted a review, later dismissed

2020-10-27 10:35 UTC, tischrei commented
recheck

2020-10-27 10:55 UTC, lego963 approved these changes

2020-10-27 11:18 UTC, merged