Rds backup
opentelekomcloud/ansible-collection-cloud pull request #55
Opened 2020-10-23 15:51 UTC by irina-pereiaslavskaia

2020-10-23 16:05 UTC, irina-pereiaslavskaia commented
recheck

2020-10-27 07:27 UTC, irina-pereiaslavskaia commented
recheck

2020-10-27 07:50 UTC, irina-pereiaslavskaia commented
recheck

2020-10-27 08:23 UTC, irina-pereiaslavskaia commented
recheck

2020-10-27 08:56 UTC, anton-sidelnikov commented on tests/integration/targets/rds_backup/tasks/main.yaml
> +          - 'rds_backup.msg == "RDS instance test-db does not exist"'
end line, and add step in with check_mode: true

2020-10-27 09:44 UTC, irina-pereiaslavskaia commented on tests/integration/targets/rds_backup/tasks/main.yaml
> +          - 'rds_backup.msg == "RDS instance test-db does not exist"'
Done

2020-10-27 09:56 UTC, anton-sidelnikov approved these changes

2020-10-28 08:06 UTC, anton-sidelnikov approved these changes

2020-10-28 11:47 UTC, gtema requested changes

2020-10-28 11:47 UTC, gtema commented on plugins/modules/rds_backup.py
> +version_added: "0.0.1"
version too old - use 0.2.0

2020-10-28 11:47 UTC, gtema commented on plugins/modules/rds_backup.py
> +- rds_backup:
use FQCN names in examples

2020-10-28 11:47 UTC, gtema commented on plugins/modules/rds_backup.py
> +      - The amount of time the module should wait.
I would say "Duration in seconds ..."

2020-10-28 12:21 UTC, irina-pereiaslavskaia commented on plugins/modules/rds_backup.py
> +- rds_backup:
Done

2020-10-28 12:21 UTC, irina-pereiaslavskaia commented on plugins/modules/rds_backup.py
> +      - The amount of time the module should wait.
Done

2020-10-28 12:21 UTC, irina-pereiaslavskaia commented on plugins/modules/rds_backup.py
> +version_added: "0.0.1"
Done

2020-10-28 12:35 UTC, anton-sidelnikov submitted a review, later dismissed

2020-11-12 13:45 UTC, anton-sidelnikov commented on tests/integration/targets/rds_backup/tasks/main.yaml
> +      rds_backup:
use fqdn name here for clients like opentelekomcloud.cloud.rds_backup

2020-11-12 13:45 UTC, anton-sidelnikov commented on plugins/modules/rds_backup.py
> +        sample: "manual"
use here 2 spaces instead of 4

2020-11-12 15:29 UTC, irina-pereiaslavskaia commented on plugins/modules/rds_backup.py
> +        sample: "manual"
Done

2020-11-12 15:29 UTC, irina-pereiaslavskaia commented on tests/integration/targets/rds_backup/tasks/main.yaml
> +      rds_backup:
Done

2020-11-12 15:40 UTC, irina-pereiaslavskaia commented
recheck

2020-11-12 15:44 UTC, lego963 commented
recheck

2020-11-12 15:49 UTC, lego963 commented
recheck

2020-11-13 07:00 UTC, anton-sidelnikov approved these changes

2020-11-13 07:27 UTC, anton-sidelnikov commented
regate

2020-11-13 08:43 UTC, anton-sidelnikov commented
regate

2020-11-13 08:55 UTC, merged