As group
opentelekomcloud/ansible-collection-cloud pull request #56
Opened 2020-10-26 08:40 UTC by Polina-Gubina

2020-10-30 07:51 UTC, Polina-Gubina commented
recheck

2020-11-03 11:37 UTC, Polina-Gubina commented
recheck

2020-11-03 12:46 UTC, Polina-Gubina commented
recheck

2020-11-05 08:23 UTC, Polina-Gubina commented
recheck

2020-11-06 13:49 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +    name: my_prod_as_group
skip if you don't wan't do describe working example

2020-11-06 13:51 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                self.fail_json(msg="Either 'lb_listener' or 'lbaas_listener' can be specified")
'or' or 'and'?

2020-11-10 15:54 UTC, tischrei requested changes

2020-11-10 15:54 UTC, tischrei commented on plugins/modules/as_group.py
> +version_added: "0.0.1"
tag version is 0.2.0

2020-11-10 15:54 UTC, tischrei commented on plugins/modules/as_group.py
> +EXAMPLES = '''
missing examples which is helpful for customers.

2020-11-10 15:54 UTC, tischrei commented on plugins/modules/as_group.py
> +        if self.params['scaling_group_name']:
Your way to go (line 267-327) is not wrong in this case, but you could keep this a bit shorter, instead of using "changed = True" in every line. Checkout this solution: https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/deh_host.py#L198 (Line 196-208). I am checking if attrs is existing and then I am changing the value of "changed" and updating the resource in one step. You can also combine the 2 if-cases with "and".

2020-11-10 15:54 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +    - name: Delete as group
Why didn't you pull this task into the "always" block? If the playbook will fail, this task won't be run.

2020-11-10 15:54 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +  always:
"ignore_errors: yes" is useful to ensure the run of all tasks inside the "always" block. Please add it.

2020-11-12 07:08 UTC, Polina-Gubina commented
recheck

2020-11-12 12:44 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +  always:
Sorry for not explaining it precisely: I meant that "ignore_errors: yes" should be provided to the whole "always block" not only 1 task. Otherweise the "always block" will not run through if an error occure.

2020-11-12 12:47 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +  always:
Please see also: https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/tests/integration/targets/nat/tasks/main.yaml to understand what I mean.

2020-11-12 12:50 UTC, tischrei requested changes

2020-11-12 12:50 UTC, tischrei commented on plugins/modules/as_group.py
> +as_group:
please use opentelekomcloud.cloud.as_group as FQCN

2020-11-12 12:53 UTC, tischrei requested changes

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +      as_group:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +      as_group:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +      as_group:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +        as_group:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +        os_router:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +        os_subnet:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +        os_network:
Please use fully qualified class name

2020-11-12 12:53 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +    loadbalancer:
Please use fully qualified class name

2020-11-12 17:26 UTC, Polina-Gubina commented on tests/integration/targets/as_group/tasks/main.yaml
> +  always:
But if router isn't deleted, it will be error when deleting subnet in the next task, the same for subnet and network, so it seems for me meaningless, but if i am not right, please let me know)

2020-11-12 18:26 UTC, Polina-Gubina commented on tests/integration/targets/as_group/tasks/main.yaml
> +      as_group:
I think you mean module name?

2020-11-13 12:40 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                    attrs['multi_az_priority_policy'] = 'equilibrium_distribute'.upper()
it uses only once, better to create some_const= 'EQUILIBRIUM_DISTRIBUTE'

2020-11-13 12:41 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                    attrs['instance_terminate_policy'] = 'old_config_old_instance'.upper()
it uses only once, better to create some_const= 'OLD_CONFIG_OLD_INSTANCE'

2020-11-13 12:42 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                    attrs['min_instance_number'] = 0
maybe better use default values?

2020-11-13 12:42 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                    attrs['max_instance_number'] = 0
default?

2020-11-13 12:43 UTC, anton-sidelnikov commented on plugins/modules/as_group.py
> +                    attrs['health_periodic_audit_grace_period'] = 600
default?

2020-11-13 13:18 UTC, tischrei approved these changes

2020-11-13 13:26 UTC, anton-sidelnikov approved these changes

2020-11-16 13:08 UTC, tischrei commented on tests/integration/targets/as_group/tasks/main.yaml
> +  always:
But if it is absent, it is meaningless ^^. So, now everything is fine from my perspective.

2020-11-16 13:11 UTC, tischrei approved these changes

2020-11-16 13:18 UTC, anton-sidelnikov approved these changes

2020-11-16 13:57 UTC, merged