AS config
opentelekomcloud/ansible-collection-cloud pull request #59
Opened 2020-10-28 14:22 UTC by Polina-Gubina

2020-10-28 14:51 UTC, Polina-Gubina commented
recheck

2020-10-29 09:19 UTC, Polina-Gubina commented
recheck

2020-10-29 11:41 UTC, Polina-Gubina commented
recheck

2020-10-29 15:57 UTC, Polina-Gubina commented
recheck

2020-10-29 20:17 UTC, Polina-Gubina commented
recheck

2020-11-06 11:28 UTC, anton-sidelnikov commented on plugins/modules/as_config.py
> +    type: str
you can use scaling_configuration_name for name and id

2020-11-06 12:50 UTC, Polina-Gubina commented on plugins/modules/as_config.py
> +    type: str
but in order to modify name, it is required to specify name and id at the same time

2020-11-06 13:28 UTC, anton-sidelnikov commented on plugins/modules/as_config.py
> +                'key_name': key_name
no need this

2020-11-06 13:45 UTC, anton-sidelnikov submitted a review, later dismissed

2020-11-06 13:45 UTC, anton-sidelnikov commented on tests/integration/targets/as_config/tasks/main.yaml
> +          state: absent
endline

2020-11-06 16:34 UTC, Polina-Gubina commented
recheck

2020-11-09 08:46 UTC, anton-sidelnikov approved these changes

2020-11-10 15:39 UTC, tischrei requested changes

2020-11-10 15:39 UTC, tischrei commented on plugins/modules/as_config.py
> +version_added: "0.0.4"
This version parameter does not mean "which version your module has". It means: "At which version of the collection has this module been added to it?". Our current version tag of opentelekomcloud.cloud collection has 0.2.0. So the version_added should be "0.2.0".

2020-11-10 15:39 UTC, tischrei commented on tests/integration/targets/as_config/tasks/main.yaml
> +    - name: Delete as config
Please use "always" block with ignore_errors yes parameter to ensure deletion of all resources when an error occure. Otherwise the playbook will abort and skip your important cleanup stuff. See also https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/tests/integration/targets/lb_certificate/tasks/main.yaml#L230 as reference.

2020-11-13 10:47 UTC, tischrei approved these changes

2020-11-13 11:00 UTC, merged