DNS Modules
opentelekomcloud/ansible-collection-cloud pull request #64
Opened 2020-11-04 10:28 UTC by SebastianGode

Still in development - just for running Tests

2020-11-13 11:09 UTC, SebastianGode commented
@tischrei Integration Test added

2020-11-13 13:42 UTC, anton-sidelnikov commented on plugins/modules/dns_floating_ip.py
> +
remove extra lines

2020-11-13 13:42 UTC, anton-sidelnikov commented on plugins/modules/dns_floating_ip.py
> +
remove extra lines

2020-11-13 14:08 UTC, anton-sidelnikov commented on plugins/modules/dns_zones.py
> +                    )
you can move that to function

2020-11-13 14:10 UTC, anton-sidelnikov commented on tests/integration/targets/dns/tasks/main.yaml
> +      dns_floating_ip:
use fqdn names in tests

2020-11-13 14:11 UTC, anton-sidelnikov requested changes
comments

2020-11-16 10:26 UTC, SebastianGode commented
This should be ready to merge now

2020-11-16 11:49 UTC, anton-sidelnikov submitted a review, later dismissed

2020-11-16 13:26 UTC, tischrei requested changes

2020-11-16 13:26 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +  always:
ignore_errors: yes is missing for whole always block

2020-11-16 13:26 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +    - name: Creating a DNS Zone
Please provide a public and a private Zone scenario.

2020-11-16 13:26 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +        - name: Drop DNS Zone
delete private and public zone

2020-11-17 08:36 UTC, tischrei requested changes

2020-11-17 08:36 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +          ignore_errors: true
Please write ignore_errors: true only once for the whole always block. Please see my NAT or DEH tests for this.

2020-11-17 08:52 UTC, tischrei requested changes
typo inside

2020-11-17 08:52 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +        git add- name: Drop dns_floating_ip entry
typo

2020-11-17 09:12 UTC, tischrei approved these changes

2020-11-17 10:36 UTC, anton-sidelnikov commented on tests/integration/targets/dns/tasks/main.yaml
> +        router_name: "{{ ( prefix + '-router' )}}"
sorry for late comment, but can you use here some suffix in names like dns? it helps to distinguish module when test resources hangs

2020-11-17 10:38 UTC, tischrei commented on tests/integration/targets/dns/tasks/main.yaml
> +        router_name: "{{ ( prefix + '-router' )}}"
don't forget "request_changes" :-D

2020-11-17 10:41 UTC, SebastianGode commented on tests/integration/targets/dns/tasks/main.yaml
> +        router_name: "{{ ( prefix + '-router' )}}"
@anton-sidelnikov I changed it so that everything has "dns" in it at the end

2020-11-17 10:43 UTC, anton-sidelnikov approved these changes

2020-11-19 10:43 UTC, tischrei approved these changes

2020-11-19 10:57 UTC, merged