CES Info Modules
opentelekomcloud/ansible-collection-cloud pull request #70
Opened 2020-11-11 13:51 UTC by SebastianGode

2020-11-11 14:03 UTC, anton-sidelnikov commented on plugins/modules/ces_alarms_info.py
> +            dt = raw.to_dict()
here raw can be null

2020-11-26 08:25 UTC, tischrei commented
recheck

2020-11-26 08:52 UTC, SebastianGode commented on plugins/modules/ces_alarms_info.py
> +            dt = raw.to_dict()
Would it make a difference if it is null? Just to understand that

2020-11-26 08:56 UTC, SebastianGode commented
I found no way to implement that as a module: https://docs.otc.t-systems.com/api/ces/en-us_topic_0032831274.html
The API somehow wants a List and even with the given Example I not managed to do it.

2020-11-26 08:58 UTC, tischrei requested changes
Please add functional tests first to check functionality

2020-11-26 08:58 UTC, tischrei commented on plugins/modules/ces_quotas_info.py
> +version_added: "0.2.1"
version is wrong

2020-11-26 08:58 UTC, tischrei commented on plugins/modules/ces_metrics_info.py
> +version_added: "0.2.1"
version is wrong

2020-11-26 08:58 UTC, tischrei commented on plugins/modules/ces_metric_data_info.py
> +version_added: "0.2.1"
version is wrong

2020-11-26 08:58 UTC, tischrei commented on plugins/modules/ces_event_data_info.py
> +version_added: "0.2.1"
version is wrong

2020-11-26 08:58 UTC, tischrei commented on plugins/modules/ces_alarms_info.py
> +version_added: "0.1.2"
version is wrong

2020-11-26 10:33 UTC, SebastianGode commented
@tischrei Integration Test added

2020-11-27 10:04 UTC, anton-sidelnikov requested changes

2020-11-27 10:04 UTC, anton-sidelnikov commented on plugins/modules/ces_quotas_info.py
> +    argument_spec = dict(
you can write an one line argument_spec = dict()

2020-11-27 10:04 UTC, anton-sidelnikov commented on plugins/modules/ces_alarms.py
> +        if self.params['state'] == 'present':
did you try disable and then enable alarm?

2020-11-27 10:10 UTC, SebastianGode commented on plugins/modules/ces_alarms.py
> +        if self.params['state'] == 'present':
Oh God, thanks!
Somehow I missed this point.

Will do that asap

2020-11-27 10:39 UTC, SebastianGode commented on plugins/modules/ces_alarms.py
> +        if self.params['state'] == 'present':
added in 4439f9a5521a2bd4ea4e65fbd0c9812da26c0f29

2020-11-27 10:39 UTC, SebastianGode commented on plugins/modules/ces_quotas_info.py
> +    argument_spec = dict(
changed in 13371b9467e97932b8ca370607a56fc46aa9dce3

2020-11-27 10:51 UTC, anton-sidelnikov approved these changes

2021-01-05 09:00 UTC, tischrei commented
recheck

2021-01-05 12:01 UTC, tischrei submitted a review, later dismissed

2021-01-06 11:04 UTC, SebastianGode commented
recheck

2021-01-08 09:06 UTC, SebastianGode commented
recheck

2021-01-08 11:10 UTC, SebastianGode commented
recheck

2021-01-08 11:22 UTC, SebastianGode commented
recheck

2021-01-08 12:47 UTC, tischrei approved these changes

2021-01-08 13:01 UTC, merged