Start using cloud layer for cce_cluster module
opentelekomcloud/ansible-collection-cloud pull request #74
Opened 2020-11-23 12:57 UTC by gtema

2020-11-23 13:49 UTC, gtema commented
recheck

2020-11-23 15:58 UTC, tischrei requested changes

2020-11-23 15:58 UTC, tischrei commented on tests/integration/targets/cce_cluster/tasks/main.yaml
> +        debug: true
clean the parameter

2020-11-23 15:58 UTC, tischrei commented on plugins/modules/cce_cluster.py
> +- name: Create cluster
Is not a sufficient example to create a cluster oob

2020-11-23 15:58 UTC, tischrei commented on tests/integration/targets/cce_cluster/tasks/main.yaml
> +    - name: assert result
Test fails with:

```
TASK [cce_cluster : assert result] ***************************************************************************************************************************************************************************
task path: /home/ubuntu/git/collections/ansible_collections/opentelekomcloud/cloud/tests/output/.tmp/integration/cce_cluster-vcdkcoaf-ÅÑŚÌβŁÈ/tests/integration/targets/cce_cluster/tasks/main.yaml:57
fatal: [testhost]: FAILED! => {
    "assertion": "cluster is changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
Read vars_file 'integration_config.yml'

TASK [cce_cluster : Drop cluster] ****************************************************************************************************************************************************************************
task path: /home/ubuntu/git/collections/ansible_collections/opentelekomcloud/cloud/tests/output/.tmp/integration/cce_cluster-vcdkcoaf-ÅÑŚÌβŁÈ/tests/integration/targets/cce_cluster/tasks/main.yaml:66
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<testhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808 `" && echo ansible-tmp-1606146821.6915188-61210-211926308515808="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808 `" ) && sleep 0'
Using module file /home/ubuntu/git/collections/ansible_collections/opentelekomcloud/cloud/plugins/modules/cce_cluster.py
<testhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-61018jrz68tf6/tmphdsl4g6w TO /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808/AnsiballZ_cce_cluster.py
<testhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808/ /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808/AnsiballZ_cce_cluster.py && sleep 0'
<testhost> EXEC /bin/sh -c '/home/ubuntu/ansiblevenv/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808/AnsiballZ_cce_cluster.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1606146821.6915188-61210-211926308515808/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_cce_cluster_payload_g0m39db5/ansible_cce_cluster_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py", line 201, in __call__
    results = self.run()
  File "/tmp/ansible_cce_cluster_payload_g0m39db5/ansible_cce_cluster_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/cce_cluster.py", line 218, in run
  File "/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/cloud/cce.py", line 199, in delete_cce_cluster
    self.cce.wait_for_job(obj.job_id, **wait_args)
  File "/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/otcextensions/sdk/cce/v3/_proxy.py", line 249, in wait_for_job
    return resource.wait_for_status(
  File "/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/openstack/resource.py", line 2091, in wait_for_status
    raise exceptions.ResourceFailure(
fatal: [testhost]: FAILED! => {
    "changed": false,
    "extra_data": {
        "data": null,
        "details": "None",
        "response": "None"
    },
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "authentication_mode": null,
            "authentication_proxy_ca": null,
            "availability_zone": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "container_network_cidr": null,
            "container_network_mode": null,
            "description": null,
            "external_ip": null,
            "flavor": null,
            "interface": "public",
            "kube_proxy_mode": null,
            "name": "z-5dd83aabe839a5ec845c5408d63ce572-acc-cce-cluster-test",
            "network": null,
            "region_name": null,
            "router": null,
            "service_ip_range": null,
            "state": "absent",
            "timeout": 1800,
            "type": "VirtualMachine",
            "validate_certs": null,
            "version": null,
            "wait": true,
            "wait_timeout": 1800
        }
    },
    "msg": "Job:0fb73d26-2da4-11eb-9ade-0255ac1017a0 transitioned to failure state Failed"
}

```

2020-11-25 11:19 UTC, gtema commented
recheck

2020-11-26 13:02 UTC, tischrei requested changes

2020-11-26 13:21 UTC, tischrei commented on tests/integration/targets/cce_cluster/tasks/main.yaml
> +      cce_cluster:
Shorten the cluster name helped.

2020-11-26 13:37 UTC, tischrei requested changes

2020-11-26 13:37 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
> +      rds_instance:
use fqcn

2020-11-26 13:37 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
> +        rds_instance:
use fqcn

2020-11-26 13:37 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
>      rds_instance:
use fqcn

2020-11-26 13:37 UTC, tischrei commented on plugins/modules/rds_instance.py
> +                changed = True
There is no way to update the flavor as it is described: https://docs.otc.t-systems.com/api/rds/rds_01_0101.html
or enlarge the volume. Those are useful operations.

2020-11-26 13:37 UTC, tischrei commented on plugins/modules/rds_instance.py
> +                    attrs['wait'] = True
Why is wait not used for creation?

2020-11-26 14:31 UTC, tischrei commented on plugins/modules/rds_instance.py
> +                    attrs['wait'] = True
Wait is failing in the testcase:

```
TASK [rds_instance : Drop instance] **************************************************************************************************************************************************************************
task path: /home/ubuntu/git/collections/ansible_collections/opentelekomcloud/cloud/tests/output/.tmp/integration/rds_instance-v5a838vt-ÅÑŚÌβŁÈ/tests/integration/targets/rds_instance/tasks/main.yaml:85
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<testhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838 `" && echo ansible-tmp-1606398404.5412514-86084-199864744893838="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838 `" ) && sleep 0'
Using module file /home/ubuntu/git/collections/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py
<testhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-85846xr126j_t/tmpm2acpqmk TO /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py
<testhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/ /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py && sleep 0'
<testhost> EXEC /bin/sh -c '/home/ubuntu/ansiblevenv/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py", line 116, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py", line 108, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py", line 54, in invoke_module
    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.rds_instance', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py", line 258, in <module>
  File "/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py", line 254, in main
  File "/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py", line 201, in __call__
  File "/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py", line 233, in run
TypeError: delete_instance() got an unexpected keyword argument 'wait'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py\", line 116, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py\", line 108, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1606398404.5412514-86084-199864744893838/AnsiballZ_rds_instance.py\", line 54, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.opentelekomcloud.cloud.plugins.modules.rds_instance', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py\", line 258, in <module>\n  File \"/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py\", line 254, in main\n  File \"/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/module_utils/otc.py\", line 201, in __call__\n  File \"/tmp/ansible_rds_instance_payload_d4gh144c/ansible_rds_instance_payload.zip/ansible_collections/opentelekomcloud/cloud/plugins/modules/rds_instance.py\", line 233, in run\nTypeError: delete_instance() got an unexpected keyword argument 'wait'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
...ignoring
Read vars_file 'integration_config.yml'
```

2020-11-26 14:32 UTC, tischrei requested changes

2020-11-26 14:32 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
>      rds_instance:
I never saw any conflicts here. We always used FQCN.

2020-11-26 14:33 UTC, tischrei commented on plugins/modules/rds_instance.py
> +                changed = True
I think, if we touch something we should finish it as far as we can.

2020-11-26 14:50 UTC, gtema commented on plugins/modules/rds_instance.py
> +                changed = True
no, no time for that now. Module was not supporting update before the change. This change is about using cloud layer for CCE module. RDS module is touched, since in scope of this work rds cloud functions got also modified

2020-11-26 15:13 UTC, tischrei requested changes

2020-11-26 15:13 UTC, tischrei commented on plugins/modules/rds_instance.py
> +                self.conn.rds.delete_rds_instance(**attrs)
RDS muss weg, sonst kein cloud layer

2020-11-26 16:09 UTC, tischrei requested changes

2020-11-26 16:09 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
> +        opentelekomcloud.cloud.rds_instance:
rds instance deletion ran into timout 600 while testing it.

2020-11-26 16:10 UTC, tischrei commented on tests/integration/targets/rds_instance/tasks/main.yaml
> +        opentelekomcloud.cloud.rds_instance:
```
  File "/home/ubuntu/ansiblevenv/lib/python3.8/site-packages/openstack/utils.py", line 68, in iterate_timeout
    raise exceptions.ResourceTimeout(message)
fatal: [testhost]: FAILED! => {
    "changed": false,
    "extra_data": {
        "data": null,
        "details": "None",
        "response": "None"
    },
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "availability_zone": null,
            "backup_keepdays": null,
            "backup_timeframe": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "configuration": null,
            "datastore_type": "postgresql",
            "datastore_version": null,
            "disk_encryption": null,
            "flavor": null,
            "ha_mode": null,
            "interface": "public",
            "name": "z-f367a3735559b0f94dab9ef5172809d9rds_test-instance",
            "network": null,
            "password": null,
            "port": null,
            "region": "eu-de",
            "region_name": null,
            "replica_of": null,
            "router": null,
            "security_group": null,
            "state": "absent",
            "validate_certs": null,
            "volume_size": null,
            "volume_type": null,
            "wait": true,
            "wait_timeout": 600
        }
    },
    "msg": "Timeout waiting for Job:d86be968-2c9a-4596-964a-997b0c71310d to transition to completed"

```

2020-11-26 16:15 UTC, tischrei approved these changes

2020-11-26 16:30 UTC, merged