Add Anti-DDoS configs module
opentelekomcloud/ansible-collection-cloud pull request #75
Opened 2020-12-01 14:26 UTC by irina-pereiaslavskaia

2020-12-01 14:55 UTC, irina-pereiaslavskaia commented
recheck

2020-12-02 08:59 UTC, anton-sidelnikov requested changes

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +module: anti_ddos_configs_info
anti_ddos_optional_policies_info

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +short_description: Get Anti-DDoS defense policies info
Get Anti-DDoS optional defense policies info

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +options: {}
i think you can skip this

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +anti_ddos_configs_info:
anti_ddos_optional_policies_info

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +- opentelekomcloud.cloud.anti_ddos_configs_info:
- opentelekomcloud.cloud.anti_ddos_optional_policies_info

2020-12-02 08:59 UTC, anton-sidelnikov commented on plugins/modules/anti_ddos_configs_info.py
> +        self.exit(changed=False, anti_ddos_configs_info=data)
anti_ddos_optional_configs_info

2020-12-02 08:59 UTC, anton-sidelnikov commented on tests/integration/targets/anti_ddos_configs_info/tasks/main.yaml
> +    - name: Get Anti-DDoS Floating IPs statuses
need proper name to step

2020-12-02 10:16 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_configs_info.py
> +module: anti_ddos_configs_info
Done

2020-12-02 10:20 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_configs_info.py
> +anti_ddos_configs_info:
Done

2020-12-02 10:20 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_configs_info.py
> +        self.exit(changed=False, anti_ddos_configs_info=data)
Done

2020-12-02 10:23 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_configs_info.py
> +- opentelekomcloud.cloud.anti_ddos_configs_info:
Done

2020-12-02 10:23 UTC, irina-pereiaslavskaia commented on tests/integration/targets/anti_ddos_configs_info/tasks/main.yaml
> +    - name: Get Anti-DDoS Floating IPs statuses
Done

2020-12-02 10:24 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_configs_info.py
> +short_description: Get Anti-DDoS defense policies info
Done

2020-12-02 10:26 UTC, tischrei requested changes

2020-12-02 10:26 UTC, tischrei commented on plugins/modules/anti_ddos_optional_policies_info.py
> +version_added: "0.2.1"
check current version

2020-12-02 10:27 UTC, anton-sidelnikov submitted a review, later dismissed

2020-12-02 10:28 UTC, tischrei commented on plugins/modules/anti_ddos_optional_policies_info.py
> +version_added: "0.2.1"
it is 4.0

2020-12-02 10:33 UTC, irina-pereiaslavskaia commented on plugins/modules/anti_ddos_optional_policies_info.py
> +version_added: "0.2.1"
Done

2020-12-02 10:54 UTC, anton-sidelnikov approved these changes

2020-12-02 11:38 UTC, tischrei approved these changes

2020-12-02 12:00 UTC, merged