Vpn services info
opentelekomcloud/ansible-collection-cloud pull request #77
Opened 2020-12-03 07:50 UTC by irina-pereiaslavskaia

2020-12-03 08:25 UTC, anton-sidelnikov commented on plugins/modules/vpn_services_info.py
> +  tenant_id:
call it project_id

2020-12-03 08:30 UTC, anton-sidelnikov requested changes

2020-12-03 08:30 UTC, anton-sidelnikov commented on plugins/modules/vpn_services_info.py
> +  tenant_id:
call it project_id

2020-12-03 08:30 UTC, anton-sidelnikov commented on tests/integration/targets/vpn_services_info/tasks/main.yaml
> +          - 'vpn_services_info.msg == "Router fake_router not found"'
add test with multiple filers

2021-01-22 14:56 UTC, irina-pereiaslavskaia commented on plugins/modules/vpn_services_info.py
> +  tenant_id:
Done

2021-01-22 14:57 UTC, irina-pereiaslavskaia commented on tests/integration/targets/vpn_services_info/tasks/main.yaml
> +          - 'vpn_services_info.msg == "Router fake_router not found"'
Done

2021-01-22 15:09 UTC, tischrei submitted a review, later dismissed
please wait for a second approval.

2021-01-22 15:20 UTC, anton-sidelnikov requested changes

2021-01-22 15:20 UTC, anton-sidelnikov commented on tests/sanity/ignore-2.9.txt
> +plugins/modules/vpn_services_info.py validate-modules:missing-gplv3-license
why duplicate?

2021-01-22 15:20 UTC, anton-sidelnikov commented on plugins/modules/vpn_service_info.py
> +  vpn_service:
check this parameter

2021-01-22 15:37 UTC, irina-pereiaslavskaia commented on tests/sanity/ignore-2.9.txt
> +plugins/modules/vpn_services_info.py validate-modules:missing-gplv3-license
Delete it

2021-01-22 15:39 UTC, anton-sidelnikov approved these changes

2021-01-25 11:04 UTC, tischrei approved these changes

2021-01-25 11:53 UTC, irina-pereiaslavskaia commented
regate

2021-01-25 12:47 UTC, irina-pereiaslavskaia commented
regate

2021-01-25 13:03 UTC, merged