New Auto Scaling Policy info module
opentelekomcloud/ansible-collection-cloud pull request #84
Opened 2021-02-02 07:42 UTC by irina-pereiaslavskaia

2021-02-02 08:28 UTC, tischrei requested changes

2021-02-02 08:28 UTC, tischrei commented on tests/integration/targets/as_policy_info/tasks/main.yaml
> +    - name: Get error when AS group id is missing
It would be more useful if your write a full integration test scenario where a as group exists and policy is checked and later the group is deleted. Otherwise the test should be disabled as it is done with cce tests: https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/tests/integration/targets/cce_lifecycle/aliases

2021-02-03 07:57 UTC, irina-pereiaslavskaia commented on tests/integration/targets/as_policy_info/tasks/main.yaml
> +    - name: Get error when AS group id is missing
Done, but while as_policy not implemented, it still checks only simplest positive and negative scenarious. I will develop as_policy as a next step and will add new checks.

2021-02-03 08:48 UTC, anton-sidelnikov requested changes

2021-02-03 08:48 UTC, anton-sidelnikov commented on plugins/modules/as_policy_info.py
> +  scaling_group_id:
you can use here universal scaling_group for searching by name and id

2021-02-03 08:50 UTC, tischrei submitted a review, later dismissed

2021-02-03 10:25 UTC, irina-pereiaslavskaia commented on plugins/modules/as_policy_info.py
> +  scaling_group_id:
Done

2021-02-03 12:15 UTC, anton-sidelnikov approved these changes

2021-02-04 07:36 UTC, Polina-Gubina approved these changes

2021-02-04 14:07 UTC, merged