Added check mode for all modules
opentelekomcloud/ansible-collection-cloud pull request #87
Opened 2021-02-15 11:54 UTC by SebastianGode

Currently just half of all Modules
WIP

2021-02-15 11:56 UTC, SebastianGode commented
Adressing Issue https://github.com/opentelekomcloud/ansible-collection-cloud/issues/86

2021-02-16 09:23 UTC, SebastianGode commented
All modules should have check_mode support now. 

I tested with the existing Integration Tests and just added `check_mode: true` where necessary. 


Info Modules generally don't change anything so check mode doesn't do anything there. Except if I misunderstood that part. As a result I just added 
```
module_kwargs = dict(
     supports_check_mode=True
)
```
to the Info Modules without changing anything else. The already existing availability_zone_info module also hasn't changed anything else (https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/availability_zone_info.py) so hopefully that's enough.

2021-02-17 10:17 UTC, gtema requested changes
Generally very good, but please also change existing integration tests that they verify this (see https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/tests/integration/targets/waf_domain/tasks/main.yaml#L97 for example)

2021-02-19 09:23 UTC, SebastianGode commented
@gtema I added integration tests for check_mode on modules where it makes sense (so no Info modules as it won't change anything).

2021-03-02 09:52 UTC, tischrei approved these changes

2021-04-06 09:05 UTC, gtema approved these changes

2021-04-07 12:15 UTC, anton-sidelnikov commented on tests/integration/targets/ces/tasks/main.yaml
> +      ignore_errors: yes
empty line

2021-04-07 12:16 UTC, anton-sidelnikov commented on tests/integration/targets/dns/tasks/main.yaml
> +      ignore_errors: yes
empty line

2021-04-07 12:16 UTC, anton-sidelnikov commented on tests/integration/targets/nat/tasks/main.yaml
> +      ignore_errors: yes
empty line

2021-04-07 12:16 UTC, anton-sidelnikov approved these changes

2021-04-30 08:18 UTC, merged