As policy module
opentelekomcloud/ansible-collection-cloud pull request #96
Opened 2021-02-24 07:15 UTC by irina-pereiaslavskaia

2021-02-24 08:19 UTC, irina-pereiaslavskaia commented
recheck

2021-02-24 10:01 UTC, irina-pereiaslavskaia commented
recheck

2021-02-24 11:20 UTC, anton-sidelnikov requested changes

2021-02-24 11:20 UTC, anton-sidelnikov commented on tests/sanity/ignore-2.9.txt
>  plugins/modules/as_config_info.py validate-modules:missing-gplv3-license
rollback this file

2021-02-24 13:15 UTC, anton-sidelnikov requested changes

2021-02-24 13:33 UTC, anton-sidelnikov requested changes

2021-02-24 13:33 UTC, anton-sidelnikov commented on plugins/modules/as_policy.py
> +        if as_group:
too deep make it more plain

2021-02-24 13:55 UTC, irina-pereiaslavskaia commented on plugins/modules/as_policy.py
> +        if launch_time:
Done

2021-02-24 15:19 UTC, lego963 requested changes

2021-02-24 15:19 UTC, lego963 commented on plugins/modules/as_policy.py
> +    state: "present"
is `state` required param in update?

2021-02-25 16:31 UTC, irina-pereiaslavskaia commented on plugins/modules/as_policy.py
> +    state: "present"
Done

2021-02-25 16:31 UTC, irina-pereiaslavskaia commented on plugins/modules/as_policy.py
> +        if as_group:
Done

2021-02-26 07:55 UTC, anton-sidelnikov approved these changes

2021-02-26 07:56 UTC, lego963 approved these changes

2021-02-26 08:19 UTC, merged