New AS instance info module
opentelekomcloud/ansible-collection-cloud pull request #98
Opened 2021-03-02 07:16 UTC by irina-pereiaslavskaia

2021-03-02 08:02 UTC, Polina-Gubina commented on plugins/modules/as_instance_info.py
> +        else:
maybe it is redundant due to 'required= True' , so it would be normal message from openstack

2021-03-02 08:05 UTC, anton-sidelnikov requested changes

2021-03-02 08:05 UTC, anton-sidelnikov commented on plugins/modules/as_instance_info.py
> +            if group:
if !group:
   self.fail(
     changed=False,
     msg='AS group %s not found' % as_group
   )

2021-03-02 08:14 UTC, Polina-Gubina commented on plugins/modules/as_instance_info.py
> +            group = self.conn.auto_scaling.find_group(
it is better to use try/catch  instead of if/else block with ...find_group( name_or_id=as_group, ignore_missing=False)

2021-03-02 08:41 UTC, irina-pereiaslavskaia commented on plugins/modules/as_instance_info.py
> +        else:
This part was deleted

2021-03-02 08:42 UTC, irina-pereiaslavskaia commented on plugins/modules/as_instance_info.py
> +            if group:
Done

2021-03-03 08:01 UTC, irina-pereiaslavskaia commented on plugins/modules/as_instance_info.py
> +            group = self.conn.auto_scaling.find_group(
Done

2021-03-03 11:01 UTC, anton-sidelnikov approved these changes

2021-03-04 08:58 UTC, anton-sidelnikov approved these changes

2021-03-04 09:04 UTC, Polina-Gubina approved these changes

2021-03-04 09:33 UTC, merged