Swift object module
opentelekomcloud/ansible-collection-cloud pull request #99
Opened 2021-03-02 07:42 UTC by Polina-Gubina

Swift object module

2021-03-02 12:57 UTC, Polina-Gubina commented
recheck

2021-03-02 14:02 UTC, anton-sidelnikov requested changes

2021-03-02 14:02 UTC, anton-sidelnikov commented on tests/integration/targets/object/tasks/main.yaml
> +    - name: Create file with content
create several different files

2021-03-02 14:02 UTC, anton-sidelnikov commented on tests/integration/targets/object/tasks/main.yaml
> +        content: "{{ content_file }}"
it works? or it should be "{{ path_file }}/{{ content_file }}"? please check

2021-03-02 14:02 UTC, anton-sidelnikov commented on tests/integration/targets/object/tasks/main.yaml
> +        content: "{{ content_file }}"
should be abs path

2021-03-03 07:46 UTC, Polina-Gubina commented
recheck

2021-03-03 08:05 UTC, anton-sidelnikov submitted a review, later dismissed

2021-03-03 09:29 UTC, lego963 submitted a review, later dismissed

2021-03-03 10:37 UTC, outcatcher requested changes

2021-03-03 10:37 UTC, outcatcher commented on plugins/modules/object.py
> +                self.fail_json("Container doesn't exist")
Usages of `self._container_exist(container)` and `self.conn.object_store.create_container` are duplicating. Can this be simplified?

2021-03-03 13:28 UTC, Polina-Gubina commented
recheck

2021-03-04 10:01 UTC, Polina-Gubina commented
recheck

2021-03-04 10:48 UTC, anton-sidelnikov approved these changes

2021-03-04 12:19 UTC, lego963 approved these changes

2021-03-04 12:27 UTC, outcatcher approved these changes

2021-03-04 15:36 UTC, gtema requested changes
1) Please separate container management into a separate module
2) Please change object upload from file to be using "source" or "src" attribute and not the "content". This can avoid lots of potential corner cases and is in sync with other ansible modules
3) If we develop it in openstack directly we can get this merged pretty quickly (but I will not insist on that, it is just effort saving).

2021-03-04 15:37 UTC, gtema commented
and then also, why do you try to compete with openstack implementation?

2021-04-08 13:59 UTC, closed without merging